/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ip4Addresses Lista adresów IPv4 w notacji dziesiętnej kropkowanej, np. `192.168.0.10`.
 * @param ip4Ranges Lista adresów IPv4 podana w formie zakresu początek–koniec, oddzielonego pojedynczym myślnikiem, np. `10.0.0.1–10.0.0.254`.
 * @param ip4Masks Lista adresów IPv4 w notacji CIDR, np. `172.16.0.0/16`.
 */


data class AllowedIps (

    /* Lista adresów IPv4 w notacji dziesiętnej kropkowanej, np. `192.168.0.10`. */
    @Json(name = "ip4Addresses")
    val ip4Addresses: kotlin.collections.List<kotlin.String>? = null,

    /* Lista adresów IPv4 podana w formie zakresu początek–koniec, oddzielonego pojedynczym myślnikiem, np. `10.0.0.1–10.0.0.254`. */
    @Json(name = "ip4Ranges")
    val ip4Ranges: kotlin.collections.List<kotlin.String>? = null,

    /* Lista adresów IPv4 w notacji CIDR, np. `172.16.0.0/16`. */
    @Json(name = "ip4Masks")
    val ip4Masks: kotlin.collections.List<kotlin.String>? = null

) {


}

