/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Metoda uwierzytelnienia. | Wartość | Opis | | --- | --- | | Token | Token KSeF. | | TrustedProfile | Profil Zaufany. | | InternalCertificate | Certyfikat KSeF. | | QualifiedSignature | Podpis kwalifikowany. | | QualifiedSeal | Pieczęć kwalifikowana. | | PersonalSignature | Podpis osobisty. | | PeppolSignature | Podpis dostawcy uslug Peppol. | 
 *
 * Values: Token,TrustedProfile,InternalCertificate,QualifiedSignature,QualifiedSeal,PersonalSignature,PeppolSignature
 */

@JsonClass(generateAdapter = false)
enum class AuthenticationMethod(val value: kotlin.String) {

    @Json(name = "Token")
    Token("Token"),

    @Json(name = "TrustedProfile")
    TrustedProfile("TrustedProfile"),

    @Json(name = "InternalCertificate")
    InternalCertificate("InternalCertificate"),

    @Json(name = "QualifiedSignature")
    QualifiedSignature("QualifiedSignature"),

    @Json(name = "QualifiedSeal")
    QualifiedSeal("QualifiedSeal"),

    @Json(name = "PersonalSignature")
    PersonalSignature("PersonalSignature"),

    @Json(name = "PeppolSignature")
    PeppolSignature("PeppolSignature");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AuthenticationMethod) "$data" else null

        /**
         * Returns a valid [AuthenticationMethod] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AuthenticationMethod? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

