/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.TokenInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken Token dostępu, którego należy używać w wywołaniach chronionych zasobów API.
 */


data class AuthenticationTokenRefreshResponse (

    /* Token dostępu, którego należy używać w wywołaniach chronionych zasobów API. */
    @Json(name = "accessToken")
    val accessToken: TokenInfo

) {


}

