/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.AuthenticationTokenStatus
import pl.com.codenow.ksefclient.models.ContextIdentifier
import pl.com.codenow.ksefclient.models.SubjectIdentifier
import pl.com.codenow.ksefclient.models.TokenPermissionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny tokena.
 * @param authorIdentifier Identyfikator osoby która wygenerowała token.
 * @param contextIdentifier Identyfikator kontekstu, w którym został wygenerowany token i do którego daje dostęp.
 * @param description Opis tokena.
 * @param requestedPermissions Uprawnienia przypisane tokenowi.
 * @param dateCreated Data i czas utworzenia tokena.
 * @param lastUseDate Data ostatniego użycia tokena.
 * @param status Status tokena. | Wartość | Opis | | --- | --- | | Pending | Token został utworzony ale jest jeszcze w trakcie aktywacji i nadawania uprawnień. Nie może być jeszcze wykorzystywany do uwierzytelniania. | | Active | Token jest aktywny i może być wykorzystywany do uwierzytelniania. | | Revoking | Token jest w trakcie unieważniania. Nie może już być wykorzystywany do uwierzytelniania. | | Revoked | Token został unieważniony i nie może być wykorzystywany do uwierzytelniania. | | Failed | Nie udało się aktywować tokena. Należy wygenerować nowy token, obecny nie może być wykorzystywany do uwierzytelniania. | 
 * @param statusDetails Dodatkowe informacje na temat statusu, zwracane w przypadku błędów.
 */


data class AuthenticationToken (

    /* Numer referencyjny tokena. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String? = null,

    /* Identyfikator osoby która wygenerowała token. */
    @Json(name = "authorIdentifier")
    val authorIdentifier: SubjectIdentifier? = null,

    /* Identyfikator kontekstu, w którym został wygenerowany token i do którego daje dostęp. */
    @Json(name = "contextIdentifier")
    val contextIdentifier: ContextIdentifier? = null,

    /* Opis tokena. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Uprawnienia przypisane tokenowi. */
    @Json(name = "requestedPermissions")
    val requestedPermissions: kotlin.collections.List<TokenPermissionType>? = null,

    /* Data i czas utworzenia tokena. */
    @Json(name = "dateCreated")
    val dateCreated: java.time.LocalDateTime? = null,

    /* Data ostatniego użycia tokena. */
    @Json(name = "lastUseDate")
    val lastUseDate: java.time.LocalDateTime? = null,

    /* Status tokena. | Wartość | Opis | | --- | --- | | Pending | Token został utworzony ale jest jeszcze w trakcie aktywacji i nadawania uprawnień. Nie może być jeszcze wykorzystywany do uwierzytelniania. | | Active | Token jest aktywny i może być wykorzystywany do uwierzytelniania. | | Revoking | Token jest w trakcie unieważniania. Nie może już być wykorzystywany do uwierzytelniania. | | Revoked | Token został unieważniony i nie może być wykorzystywany do uwierzytelniania. | | Failed | Nie udało się aktywować tokena. Należy wygenerować nowy token, obecny nie może być wykorzystywany do uwierzytelniania. |  */
    @Json(name = "status")
    val status: AuthenticationTokenStatus? = null,

    /* Dodatkowe informacje na temat statusu, zwracane w przypadku błędów. */
    @Json(name = "statusDetails")
    val statusDetails: kotlin.collections.List<kotlin.String>? = null

) {


}

