/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.TokenInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accessToken Token dostępu.
 * @param refreshToken Token umożliwiający odświeżenie tokenu dostępu. > Więcej informacji: > - [Odświeżanie tokena](https://github.com/CIRFMF/ksef-docs/blob/main/uwierzytelnianie.md#od%C5%9Bwie%C5%BCenie-tokena-accesstoken)
 */


data class AuthenticationTokensResponse (

    /* Token dostępu. */
    @Json(name = "accessToken")
    val accessToken: TokenInfo,

    /* Token umożliwiający odświeżenie tokenu dostępu. > Więcej informacji: > - [Odświeżanie tokena](https://github.com/CIRFMF/ksef-docs/blob/main/uwierzytelnianie.md#od%C5%9Bwie%C5%BCenie-tokena-accesstoken) */
    @Json(name = "refreshToken")
    val refreshToken: TokenInfo

) {


}

