/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.BatchFilePartInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fileSize Rozmiar pliku paczki w bajtach. Maksymalny rozmiar paczki to 5GiB (5 368 709 120 bajtów).
 * @param fileHash Skrót SHA256 pliku paczki, zakodowany w formacie Base64.
 * @param fileParts Informacje o częściach pliku paczki. Maksymalna liczba części to 50.
 */


data class BatchFileInfo (

    /* Rozmiar pliku paczki w bajtach. Maksymalny rozmiar paczki to 5GiB (5 368 709 120 bajtów). */
    @Json(name = "fileSize")
    val fileSize: kotlin.Long,

    /* Skrót SHA256 pliku paczki, zakodowany w formacie Base64. */
    @Json(name = "fileHash")
    val fileHash: kotlin.String,

    /* Informacje o częściach pliku paczki. Maksymalna liczba części to 50. */
    @Json(name = "fileParts")
    val fileParts: kotlin.collections.List<BatchFilePartInfo>

) {


}

