/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param commonName Nazwa powszechna.
 * @param countryName Kraj, kod ISO 3166.
 * @param givenName Imię.
 * @param surname Nazwisko.
 * @param serialNumber Numer seryjny podmiotu.
 * @param uniqueIdentifier Unikalny identyfikator.
 * @param organizationName Nazwa organizacji.
 * @param organizationIdentifier Identyfikator organizacji.
 */


data class CertificateEnrollmentDataResponse (

    /* Nazwa powszechna. */
    @Json(name = "commonName")
    val commonName: kotlin.String,

    /* Kraj, kod ISO 3166. */
    @Json(name = "countryName")
    val countryName: kotlin.String,

    /* Imię. */
    @Json(name = "givenName")
    val givenName: kotlin.String? = null,

    /* Nazwisko. */
    @Json(name = "surname")
    val surname: kotlin.String? = null,

    /* Numer seryjny podmiotu. */
    @Json(name = "serialNumber")
    val serialNumber: kotlin.String? = null,

    /* Unikalny identyfikator. */
    @Json(name = "uniqueIdentifier")
    val uniqueIdentifier: kotlin.String? = null,

    /* Nazwa organizacji. */
    @Json(name = "organizationName")
    val organizationName: kotlin.String? = null,

    /* Identyfikator organizacji. */
    @Json(name = "organizationIdentifier")
    val organizationIdentifier: kotlin.String? = null

) {


}

