/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.StatusInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestDate Data złożenia wniosku certyfikacyjnego.
 * @param status Informacje o aktualnym statusie. | Code | Description | Details | | --- | --- | --- | | 100 | Wniosek przyjęty do realizacji | - | | 200 | Wniosek obsłużony (certyfikat wygenerowany) | - | | 400 | Wniosek odrzucony | Klucz publiczny został już certyfikowany przez inny podmiot. | | 400 | Wniosek odrzucony | Osiągnięto dopuszczalny limit posiadanych certyfikatów. | | 500 | Nieznany błąd | - |
 * @param certificateSerialNumber Numer seryjny wygenerowanego certyfikatu (w formacie szesnastkowym).  Zwracany w przypadku prawidłowego przeprocesowania wniosku certyfikacyjnego.
 */


data class CertificateEnrollmentStatusResponse (

    /* Data złożenia wniosku certyfikacyjnego. */
    @Json(name = "requestDate")
    val requestDate: java.time.LocalDateTime,

    /* Informacje o aktualnym statusie. | Code | Description | Details | | --- | --- | --- | | 100 | Wniosek przyjęty do realizacji | - | | 200 | Wniosek obsłużony (certyfikat wygenerowany) | - | | 400 | Wniosek odrzucony | Klucz publiczny został już certyfikowany przez inny podmiot. | | 400 | Wniosek odrzucony | Osiągnięto dopuszczalny limit posiadanych certyfikatów. | | 500 | Nieznany błąd | - | */
    @Json(name = "status")
    val status: StatusInfo,

    /* Numer seryjny wygenerowanego certyfikatu (w formacie szesnastkowym).  Zwracany w przypadku prawidłowego przeprocesowania wniosku certyfikacyjnego. */
    @Json(name = "certificateSerialNumber")
    val certificateSerialNumber: kotlin.String? = null

) {


}

