/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.CertificateListItemStatus
import pl.com.codenow.ksefclient.models.KsefCertificateType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param certificateSerialNumber Numer seryjny certyfikatu (w formacie szesnastkowym).
 * @param name Nazwa własna certyfikatu.
 * @param type Typ certyfikatu. | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline | 
 * @param commonName Nazwa powszechna (CN) podmiotu, dla którego wystawiono certyfikat.
 * @param status Status certyfikatu. | Wartość | Opis | | --- | --- | | Active | Certyfikat jest aktywny i może zostać użyty do uwierzytelnienia lub realizacji operacji w trybie offline (w zależności od typu certyfikatu). | | Blocked | Certyfikat został zablokowany i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline.            Status przejściowy do czasu zakończenia procesu unieważniania. | | Revoked | Certyfikat został unieważniony i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline. | | Expired | Certyfikat wygasł i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline. | 
 * @param subjectIdentifier Identyfikator podmiotu, dla którego wystawiono certyfikat.
 * @param subjectIdentifierType Typ identyfikatora podmiotu, dla którego wystawiono certyfikat.
 * @param validFrom Data rozpoczęcia ważności certyfikatu.
 * @param validTo Data wygaśnięcia certyfikatu.
 * @param lastUseDate Data ostatniego użycia certyfikatu.
 */


data class CertificateListItem (

    /* Numer seryjny certyfikatu (w formacie szesnastkowym). */
    @Json(name = "certificateSerialNumber")
    val certificateSerialNumber: kotlin.String,

    /* Nazwa własna certyfikatu. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Typ certyfikatu. | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline |  */
    @Json(name = "type")
    val type: KsefCertificateType,

    /* Nazwa powszechna (CN) podmiotu, dla którego wystawiono certyfikat. */
    @Json(name = "commonName")
    val commonName: kotlin.String,

    /* Status certyfikatu. | Wartość | Opis | | --- | --- | | Active | Certyfikat jest aktywny i może zostać użyty do uwierzytelnienia lub realizacji operacji w trybie offline (w zależności od typu certyfikatu). | | Blocked | Certyfikat został zablokowany i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline.            Status przejściowy do czasu zakończenia procesu unieważniania. | | Revoked | Certyfikat został unieważniony i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline. | | Expired | Certyfikat wygasł i nie może zostać użyty do uwierzytelnienia i realizacji operacji w trybie offline. |  */
    @Json(name = "status")
    val status: CertificateListItemStatus,

    /* Identyfikator podmiotu, dla którego wystawiono certyfikat. */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: kotlin.String,

    /* Typ identyfikatora podmiotu, dla którego wystawiono certyfikat. */
    @Json(name = "subjectIdentifierType")
    val subjectIdentifierType: kotlin.String,

    /* Data rozpoczęcia ważności certyfikatu. */
    @Json(name = "validFrom")
    val validFrom: java.time.LocalDateTime,

    /* Data wygaśnięcia certyfikatu. */
    @Json(name = "validTo")
    val validTo: java.time.LocalDateTime,

    /* Data ostatniego użycia certyfikatu. */
    @Json(name = "lastUseDate")
    val lastUseDate: java.time.LocalDateTime? = null

) {


}

