/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param remaining Pozostała wartość limitu.
 * @param limit Maksymalna liczba zasobów dozwolona w ramach limitu.
 */


data class CertificateLimit (

    /* Pozostała wartość limitu. */
    @Json(name = "remaining")
    val remaining: kotlin.Int,

    /* Maksymalna liczba zasobów dozwolona w ramach limitu. */
    @Json(name = "limit")
    val limit: kotlin.Int

) {


}

