/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.CertificateLimit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Informacje o limitach wniosków oraz certyfikatów dla uwierzytelnionego podmiotu.
 *
 * @param canRequest Flaga informująca czy uwierzytelniony podmiot może złożyć nowy wniosek o certyfikat.
 * @param enrollment Informacje o limitach związanych z liczbą możliwych do złożenia wniosków certyfikacyjnych.
 * @param certificate Informacje o limitach dotyczących liczby aktywnych certyfikatów wydanych dla danego podmiotu.
 */


data class CertificateLimitsResponse (

    /* Flaga informująca czy uwierzytelniony podmiot może złożyć nowy wniosek o certyfikat. */
    @Json(name = "canRequest")
    val canRequest: kotlin.Boolean,

    /* Informacje o limitach związanych z liczbą możliwych do złożenia wniosków certyfikacyjnych. */
    @Json(name = "enrollment")
    val enrollment: CertificateLimit,

    /* Informacje o limitach dotyczących liczby aktywnych certyfikatów wydanych dla danego podmiotu. */
    @Json(name = "certificate")
    val certificate: CertificateLimit

) {


}

