/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isAttachmentAllowed Informacja czy Podmiot ma obecnie możliwość dodawania Załączników do Faktur
 * @param revokedDate Data i czas zakończenia możliwość dodawania przez Podmiot Załączników do Faktur. Brak podanej daty oznacza bezterminową możliwość dodawania Załączników do Faktur
 */


data class CheckAttachmentPermissionStatusResponse (

    /* Informacja czy Podmiot ma obecnie możliwość dodawania Załączników do Faktur */
    @Json(name = "isAttachmentAllowed")
    val isAttachmentAllowed: kotlin.Boolean? = null,

    /* Data i czas zakończenia możliwość dodawania przez Podmiot Załączników do Faktur. Brak podanej daty oznacza bezterminową możliwość dodawania Załączników do Faktur */
    @Json(name = "revokedDate")
    val revokedDate: java.time.LocalDateTime? = null

) {


}

