/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BOV,BRL,BSD,BTN,BWP,BYN,BZD,CAD,CDF,CHE,CHF,CHW,CLF,CLP,CNY,COP,COU,CRC,CUC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEL,GGP,GHS,GIP,GMD,GNF,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,IMP,INR,IQD,IRR,ISK,JEP,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRU,MUR,MVR,MWK,MXN,MXV,MYR,MZN,NAD,NGN,NIO,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SLL,SOS,SRD,SSP,STN,SVC,SYP,SZL,THB,TJS,TMT,TND,TOP,TRY,TTD,TWD,TZS,UAH,UGX,USD,USN,UYI,UYU,UYW,UZS,VES,VND,VUV,WST,XAF,XAG,XAU,XBA,XBB,XBC,XBD,XCD,XCG,XDR,XOF,XPD,XPF,XPT,XSU,XUA,XXX,YER,ZAR,ZMW,ZWL
 */

@JsonClass(generateAdapter = false)
enum class CurrencyCode(val value: kotlin.String) {

    @Json(name = "AED")
    AED("AED"),

    @Json(name = "AFN")
    AFN("AFN"),

    @Json(name = "ALL")
    ALL("ALL"),

    @Json(name = "AMD")
    AMD("AMD"),

    @Json(name = "ANG")
    ANG("ANG"),

    @Json(name = "AOA")
    AOA("AOA"),

    @Json(name = "ARS")
    ARS("ARS"),

    @Json(name = "AUD")
    AUD("AUD"),

    @Json(name = "AWG")
    AWG("AWG"),

    @Json(name = "AZN")
    AZN("AZN"),

    @Json(name = "BAM")
    BAM("BAM"),

    @Json(name = "BBD")
    BBD("BBD"),

    @Json(name = "BDT")
    BDT("BDT"),

    @Json(name = "BGN")
    BGN("BGN"),

    @Json(name = "BHD")
    BHD("BHD"),

    @Json(name = "BIF")
    BIF("BIF"),

    @Json(name = "BMD")
    BMD("BMD"),

    @Json(name = "BND")
    BND("BND"),

    @Json(name = "BOB")
    BOB("BOB"),

    @Json(name = "BOV")
    BOV("BOV"),

    @Json(name = "BRL")
    BRL("BRL"),

    @Json(name = "BSD")
    BSD("BSD"),

    @Json(name = "BTN")
    BTN("BTN"),

    @Json(name = "BWP")
    BWP("BWP"),

    @Json(name = "BYN")
    BYN("BYN"),

    @Json(name = "BZD")
    BZD("BZD"),

    @Json(name = "CAD")
    CAD("CAD"),

    @Json(name = "CDF")
    CDF("CDF"),

    @Json(name = "CHE")
    CHE("CHE"),

    @Json(name = "CHF")
    CHF("CHF"),

    @Json(name = "CHW")
    CHW("CHW"),

    @Json(name = "CLF")
    CLF("CLF"),

    @Json(name = "CLP")
    CLP("CLP"),

    @Json(name = "CNY")
    CNY("CNY"),

    @Json(name = "COP")
    COP("COP"),

    @Json(name = "COU")
    COU("COU"),

    @Json(name = "CRC")
    CRC("CRC"),

    @Json(name = "CUC")
    CUC("CUC"),

    @Json(name = "CUP")
    CUP("CUP"),

    @Json(name = "CVE")
    CVE("CVE"),

    @Json(name = "CZK")
    CZK("CZK"),

    @Json(name = "DJF")
    DJF("DJF"),

    @Json(name = "DKK")
    DKK("DKK"),

    @Json(name = "DOP")
    DOP("DOP"),

    @Json(name = "DZD")
    DZD("DZD"),

    @Json(name = "EGP")
    EGP("EGP"),

    @Json(name = "ERN")
    ERN("ERN"),

    @Json(name = "ETB")
    ETB("ETB"),

    @Json(name = "EUR")
    EUR("EUR"),

    @Json(name = "FJD")
    FJD("FJD"),

    @Json(name = "FKP")
    FKP("FKP"),

    @Json(name = "GBP")
    GBP("GBP"),

    @Json(name = "GEL")
    GEL("GEL"),

    @Json(name = "GGP")
    GGP("GGP"),

    @Json(name = "GHS")
    GHS("GHS"),

    @Json(name = "GIP")
    GIP("GIP"),

    @Json(name = "GMD")
    GMD("GMD"),

    @Json(name = "GNF")
    GNF("GNF"),

    @Json(name = "GTQ")
    GTQ("GTQ"),

    @Json(name = "GYD")
    GYD("GYD"),

    @Json(name = "HKD")
    HKD("HKD"),

    @Json(name = "HNL")
    HNL("HNL"),

    @Json(name = "HRK")
    HRK("HRK"),

    @Json(name = "HTG")
    HTG("HTG"),

    @Json(name = "HUF")
    HUF("HUF"),

    @Json(name = "IDR")
    IDR("IDR"),

    @Json(name = "ILS")
    ILS("ILS"),

    @Json(name = "IMP")
    IMP("IMP"),

    @Json(name = "INR")
    INR("INR"),

    @Json(name = "IQD")
    IQD("IQD"),

    @Json(name = "IRR")
    IRR("IRR"),

    @Json(name = "ISK")
    ISK("ISK"),

    @Json(name = "JEP")
    JEP("JEP"),

    @Json(name = "JMD")
    JMD("JMD"),

    @Json(name = "JOD")
    JOD("JOD"),

    @Json(name = "JPY")
    JPY("JPY"),

    @Json(name = "KES")
    KES("KES"),

    @Json(name = "KGS")
    KGS("KGS"),

    @Json(name = "KHR")
    KHR("KHR"),

    @Json(name = "KMF")
    KMF("KMF"),

    @Json(name = "KPW")
    KPW("KPW"),

    @Json(name = "KRW")
    KRW("KRW"),

    @Json(name = "KWD")
    KWD("KWD"),

    @Json(name = "KYD")
    KYD("KYD"),

    @Json(name = "KZT")
    KZT("KZT"),

    @Json(name = "LAK")
    LAK("LAK"),

    @Json(name = "LBP")
    LBP("LBP"),

    @Json(name = "LKR")
    LKR("LKR"),

    @Json(name = "LRD")
    LRD("LRD"),

    @Json(name = "LSL")
    LSL("LSL"),

    @Json(name = "LYD")
    LYD("LYD"),

    @Json(name = "MAD")
    MAD("MAD"),

    @Json(name = "MDL")
    MDL("MDL"),

    @Json(name = "MGA")
    MGA("MGA"),

    @Json(name = "MKD")
    MKD("MKD"),

    @Json(name = "MMK")
    MMK("MMK"),

    @Json(name = "MNT")
    MNT("MNT"),

    @Json(name = "MOP")
    MOP("MOP"),

    @Json(name = "MRU")
    MRU("MRU"),

    @Json(name = "MUR")
    MUR("MUR"),

    @Json(name = "MVR")
    MVR("MVR"),

    @Json(name = "MWK")
    MWK("MWK"),

    @Json(name = "MXN")
    MXN("MXN"),

    @Json(name = "MXV")
    MXV("MXV"),

    @Json(name = "MYR")
    MYR("MYR"),

    @Json(name = "MZN")
    MZN("MZN"),

    @Json(name = "NAD")
    NAD("NAD"),

    @Json(name = "NGN")
    NGN("NGN"),

    @Json(name = "NIO")
    NIO("NIO"),

    @Json(name = "NOK")
    NOK("NOK"),

    @Json(name = "NPR")
    NPR("NPR"),

    @Json(name = "NZD")
    NZD("NZD"),

    @Json(name = "OMR")
    OMR("OMR"),

    @Json(name = "PAB")
    PAB("PAB"),

    @Json(name = "PEN")
    PEN("PEN"),

    @Json(name = "PGK")
    PGK("PGK"),

    @Json(name = "PHP")
    PHP("PHP"),

    @Json(name = "PKR")
    PKR("PKR"),

    @Json(name = "PLN")
    PLN("PLN"),

    @Json(name = "PYG")
    PYG("PYG"),

    @Json(name = "QAR")
    QAR("QAR"),

    @Json(name = "RON")
    RON("RON"),

    @Json(name = "RSD")
    RSD("RSD"),

    @Json(name = "RUB")
    RUB("RUB"),

    @Json(name = "RWF")
    RWF("RWF"),

    @Json(name = "SAR")
    SAR("SAR"),

    @Json(name = "SBD")
    SBD("SBD"),

    @Json(name = "SCR")
    SCR("SCR"),

    @Json(name = "SDG")
    SDG("SDG"),

    @Json(name = "SEK")
    SEK("SEK"),

    @Json(name = "SGD")
    SGD("SGD"),

    @Json(name = "SHP")
    SHP("SHP"),

    @Json(name = "SLL")
    SLL("SLL"),

    @Json(name = "SOS")
    SOS("SOS"),

    @Json(name = "SRD")
    SRD("SRD"),

    @Json(name = "SSP")
    SSP("SSP"),

    @Json(name = "STN")
    STN("STN"),

    @Json(name = "SVC")
    SVC("SVC"),

    @Json(name = "SYP")
    SYP("SYP"),

    @Json(name = "SZL")
    SZL("SZL"),

    @Json(name = "THB")
    THB("THB"),

    @Json(name = "TJS")
    TJS("TJS"),

    @Json(name = "TMT")
    TMT("TMT"),

    @Json(name = "TND")
    TND("TND"),

    @Json(name = "TOP")
    TOP("TOP"),

    @Json(name = "TRY")
    TRY("TRY"),

    @Json(name = "TTD")
    TTD("TTD"),

    @Json(name = "TWD")
    TWD("TWD"),

    @Json(name = "TZS")
    TZS("TZS"),

    @Json(name = "UAH")
    UAH("UAH"),

    @Json(name = "UGX")
    UGX("UGX"),

    @Json(name = "USD")
    USD("USD"),

    @Json(name = "USN")
    USN("USN"),

    @Json(name = "UYI")
    UYI("UYI"),

    @Json(name = "UYU")
    UYU("UYU"),

    @Json(name = "UYW")
    UYW("UYW"),

    @Json(name = "UZS")
    UZS("UZS"),

    @Json(name = "VES")
    VES("VES"),

    @Json(name = "VND")
    VND("VND"),

    @Json(name = "VUV")
    VUV("VUV"),

    @Json(name = "WST")
    WST("WST"),

    @Json(name = "XAF")
    XAF("XAF"),

    @Json(name = "XAG")
    XAG("XAG"),

    @Json(name = "XAU")
    XAU("XAU"),

    @Json(name = "XBA")
    XBA("XBA"),

    @Json(name = "XBB")
    XBB("XBB"),

    @Json(name = "XBC")
    XBC("XBC"),

    @Json(name = "XBD")
    XBD("XBD"),

    @Json(name = "XCD")
    XCD("XCD"),

    @Json(name = "XCG")
    XCG("XCG"),

    @Json(name = "XDR")
    XDR("XDR"),

    @Json(name = "XOF")
    XOF("XOF"),

    @Json(name = "XPD")
    XPD("XPD"),

    @Json(name = "XPF")
    XPF("XPF"),

    @Json(name = "XPT")
    XPT("XPT"),

    @Json(name = "XSU")
    XSU("XSU"),

    @Json(name = "XUA")
    XUA("XUA"),

    @Json(name = "XXX")
    XXX("XXX"),

    @Json(name = "YER")
    YER("YER"),

    @Json(name = "ZAR")
    ZAR("ZAR"),

    @Json(name = "ZMW")
    ZMW("ZMW"),

    @Json(name = "ZWL")
    ZWL("ZWL");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CurrencyCode) "$data" else null

        /**
         * Returns a valid [CurrencyCode] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CurrencyCode? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

