/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param encryptedSymmetricKey Klucz symetryczny zaszyfrowany algorytmem RSA (Padding: OAEP z SHA-256), zakodowany w formacie Base64.  [Klucz publiczny RSA](/public-keys/publicKey.pem)
 * @param initializationVector Wektor inicjalizujący (IV) używany do szyfrowania symetrycznego, zakodowany w formacie Base64.
 */


data class EncryptionInfo (

    /* Klucz symetryczny zaszyfrowany algorytmem RSA (Padding: OAEP z SHA-256), zakodowany w formacie Base64.  [Klucz publiczny RSA](/public-keys/publicKey.pem) */
    @Json(name = "encryptedSymmetricKey")
    val encryptedSymmetricKey: kotlin.String,

    /* Wektor inicjalizujący (IV) używany do szyfrowania symetrycznego, zakodowany w formacie Base64. */
    @Json(name = "initializationVector")
    val initializationVector: kotlin.String

) {


}

