/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.KsefCertificateType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param certificateName Nazwa własna certyfikatu.
 * @param certificateType Typ certyfikatu. | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline | 
 * @param csr Wniosek certyfikacyjny PKCS#10 (CSR) w formacie DER zakodowany w Base64.
 * @param validFrom Data rozpoczęcia ważności certyfikatu. Jeśli nie zostanie podana, certyfikat będzie ważny od momentu jego wystawienia.
 */


data class EnrollCertificateRequest (

    /* Nazwa własna certyfikatu. */
    @Json(name = "certificateName")
    val certificateName: kotlin.String,

    /* Typ certyfikatu. | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline |  */
    @Json(name = "certificateType")
    val certificateType: KsefCertificateType,

    /* Wniosek certyfikacyjny PKCS#10 (CSR) w formacie DER zakodowany w Base64. */
    @Json(name = "csr")
    val csr: kotlin.ByteArray,

    /* Data rozpoczęcia ważności certyfikatu. Jeśli nie zostanie podana, certyfikat będzie ważny od momentu jego wystawienia. */
    @Json(name = "validFrom")
    val validFrom: java.time.LocalDateTime? = null

) {


}

