/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny operacji przetwarzania wniosku certyfikacyjnego.
 * @param timestamp Data złożenia wniosku certyfikacyjnego.
 */


data class EnrollCertificateResponse (

    /* Numer referencyjny operacji przetwarzania wniosku certyfikacyjnego. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String,

    /* Data złożenia wniosku certyfikacyjnego. */
    @Json(name = "timestamp")
    val timestamp: java.time.LocalDateTime

) {


}

