/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorIdentifierType
import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorizedEntityIdentifierType
import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorizingEntityIdentifierType
import pl.com.codenow.ksefclient.models.InvoicePermissionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identyfikator uprawnienia.
 * @param authorizedEntityIdentifier Identyfikator podmiotu uprawnionego.
 * @param authorizedEntityIdentifierType Typ identyfikatora podmiotu uprawnionego.
 * @param authorizingEntityIdentifier Identyfikator podmiotu uprawniającego.
 * @param authorizingEntityIdentifierType Typ identyfikatora podmiotu uprawniającego.
 * @param authorizationScope Uprawnienie.
 * @param description Opis uprawnienia.
 * @param startDate Data rozpoczęcia obowiązywania uprawnienia.
 * @param authorIdentifier Identyfikator osoby nadającej uprawnienie.
 * @param authorIdentifierType Typ identyfikatora osoby nadającej uprawnienie.
 */


data class EntityAuthorizationGrant (

    /* Identyfikator uprawnienia. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Identyfikator podmiotu uprawnionego. */
    @Json(name = "authorizedEntityIdentifier")
    val authorizedEntityIdentifier: kotlin.String,

    /* Typ identyfikatora podmiotu uprawnionego. */
    @Json(name = "authorizedEntityIdentifierType")
    val authorizedEntityIdentifierType: EntityAuthorizationsAuthorizedEntityIdentifierType,

    /* Identyfikator podmiotu uprawniającego. */
    @Json(name = "authorizingEntityIdentifier")
    val authorizingEntityIdentifier: kotlin.String,

    /* Typ identyfikatora podmiotu uprawniającego. */
    @Json(name = "authorizingEntityIdentifierType")
    val authorizingEntityIdentifierType: EntityAuthorizationsAuthorizingEntityIdentifierType,

    /* Uprawnienie. */
    @Json(name = "authorizationScope")
    val authorizationScope: InvoicePermissionType,

    /* Opis uprawnienia. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Data rozpoczęcia obowiązywania uprawnienia. */
    @Json(name = "startDate")
    val startDate: java.time.LocalDateTime,

    /* Identyfikator osoby nadającej uprawnienie. */
    @Json(name = "authorIdentifier")
    val authorIdentifier: kotlin.String? = null,

    /* Typ identyfikatora osoby nadającej uprawnienie. */
    @Json(name = "authorIdentifierType")
    val authorIdentifierType: EntityAuthorizationsAuthorIdentifierType? = null

) {


}

