/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityPermissionType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type Możliwe uprawnienia do nadania.
 * @param canDelegate Flaga pozwalająca na pośrednie przekazywanie danego uprawnienia
 */


data class EntityPermission (

    /* Możliwe uprawnienia do nadania. */
    @Json(name = "type")
    val type: EntityPermissionType,

    /* Flaga pozwalająca na pośrednie przekazywanie danego uprawnienia */
    @Json(name = "canDelegate")
    val canDelegate: kotlin.Boolean? = null

) {


}

