/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorizingEntityIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Identyfikator podmiotu uprawniającego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
 *
 * @param type Typ identyfikatora.
 * @param `value` Wartość identyfikatora.
 */


data class EntityAuthorizationsAuthorizingEntityIdentifier (

    /* Typ identyfikatora. */
    @Json(name = "type")
    val type: EntityAuthorizationsAuthorizingEntityIdentifierType,

    /* Wartość identyfikatora. */
    @Json(name = "value")
    val `value`: kotlin.String

) {


}

