/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionType
import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionsSubjectIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectIdentifier Identyfikator podmiotu. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
 * @param permission Nadawane uprawnienie o charakterze upoważnienia.
 * @param description Opis nadawanego uprawnienia.
 */


data class EntityAuthorizationPermissionsGrantRequest (

    /* Identyfikator podmiotu. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: EntityAuthorizationPermissionsSubjectIdentifier,

    /* Nadawane uprawnienie o charakterze upoważnienia. */
    @Json(name = "permission")
    val permission: EntityAuthorizationPermissionType,

    /* Opis nadawanego uprawnienia. */
    @Json(name = "description")
    val description: kotlin.String

) {


}

