/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityPermission
import pl.com.codenow.ksefclient.models.EntityPermissionsSubjectIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectIdentifier Identyfikator podmiotu. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
 * @param permissions Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
 * @param description Opis nadawanych uprawnień.
 */


data class EntityPermissionsGrantRequest (

    /* Identyfikator podmiotu. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: EntityPermissionsSubjectIdentifier,

    /* Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz. */
    @Json(name = "permissions")
    val permissions: kotlin.collections.List<EntityPermission>,

    /* Opis nadawanych uprawnień. */
    @Json(name = "description")
    val description: kotlin.String

) {


}

