/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorizedEntityIdentifier
import pl.com.codenow.ksefclient.models.EntityAuthorizationsAuthorizingEntityIdentifier
import pl.com.codenow.ksefclient.models.InvoicePermissionType
import pl.com.codenow.ksefclient.models.QueryType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param queryType Typ zapytania. | Type | Value | | --- | --- | | Granted | Uprawnienia nadane innym podmiotom | | Received | Uprawnienia otrzymane od innych podmiotów |
 * @param authorizingIdentifier Identyfikator podmiotu uprawniającego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
 * @param authorizedIdentifier Identyfikator podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | PeppolId | Identyfikator dostawcy usług Peppol |
 * @param permissionTypes Możliwe uprawnienia do filtrowania.
 */


data class EntityAuthorizationPermissionsQueryRequest (

    /* Typ zapytania. | Type | Value | | --- | --- | | Granted | Uprawnienia nadane innym podmiotom | | Received | Uprawnienia otrzymane od innych podmiotów | */
    @Json(name = "queryType")
    val queryType: QueryType,

    /* Identyfikator podmiotu uprawniającego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | */
    @Json(name = "authorizingIdentifier")
    val authorizingIdentifier: EntityAuthorizationsAuthorizingEntityIdentifier? = null,

    /* Identyfikator podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | PeppolId | Identyfikator dostawcy usług Peppol | */
    @Json(name = "authorizedIdentifier")
    val authorizedIdentifier: EntityAuthorizationsAuthorizedEntityIdentifier? = null,

    /* Możliwe uprawnienia do filtrowania. */
    @Json(name = "permissionTypes")
    val permissionTypes: kotlin.collections.List<InvoicePermissionType>? = null

) {


}

