/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EuEntityAdministrationPermissionsContextIdentifier
import pl.com.codenow.ksefclient.models.EuEntityAdministrationPermissionsSubjectIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectIdentifier Identyfikator podmiotu. | Type | Value | | --- | --- | | Fingerprint | Odcisk palca certyfikatu |
 * @param contextIdentifier Identyfikator zlożony z podmiotu polskiego i podmiotu unijnego. | Type | Value | | --- | --- | | NipVatUe | Dwuczłonowy identyfikator składający się z numeru NIP i numeru VAT-UE: `{nip}-{vat_ue}` |
 * @param description Opis nadawanych uprawnień.
 * @param subjectName Nazwa podmiotu.
 */


data class EuEntityAdministrationPermissionsGrantRequest (

    /* Identyfikator podmiotu. | Type | Value | | --- | --- | | Fingerprint | Odcisk palca certyfikatu | */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: EuEntityAdministrationPermissionsSubjectIdentifier,

    /* Identyfikator zlożony z podmiotu polskiego i podmiotu unijnego. | Type | Value | | --- | --- | | NipVatUe | Dwuczłonowy identyfikator składający się z numeru NIP i numeru VAT-UE: `{nip}-{vat_ue}` | */
    @Json(name = "contextIdentifier")
    val contextIdentifier: EuEntityAdministrationPermissionsContextIdentifier,

    /* Opis nadawanych uprawnień. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Nazwa podmiotu. */
    @Json(name = "subjectName")
    val subjectName: kotlin.String

) {


}

