/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.ExceptionDetails

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param exceptionDetailList 
 * @param referenceNumber 
 * @param serviceCode 
 * @param serviceCtx 
 * @param serviceName 
 * @param timestamp 
 */


data class ExceptionInfo (

    @Json(name = "exceptionDetailList")
    val exceptionDetailList: kotlin.collections.List<ExceptionDetails>? = null,

    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String? = null,

    @Json(name = "serviceCode")
    val serviceCode: kotlin.String? = null,

    @Json(name = "serviceCtx")
    val serviceCtx: kotlin.String? = null,

    @Json(name = "serviceName")
    val serviceName: kotlin.String? = null,

    @Json(name = "timestamp")
    val timestamp: java.time.LocalDateTime? = null

) {


}

