/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param systemCode Kod systemowy
 * @param schemaVersion Wersja schematu
 * @param `value` Wartość
 */


data class FormCode (

    /* Kod systemowy */
    @Json(name = "systemCode")
    val systemCode: kotlin.String,

    /* Wersja schematu */
    @Json(name = "schemaVersion")
    val schemaVersion: kotlin.String,

    /* Wartość */
    @Json(name = "value")
    val `value`: kotlin.String

) {


}

