/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny tokena KSeF. Za jego pomocą można sprawdzić jego status lub go unieważnić.
 * @param token Token KSeF.
 */


data class GenerateTokenResponse (

    /* Numer referencyjny tokena KSeF. Za jego pomocą można sprawdzić jego status lub go unieważnić. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String? = null,

    /* Token KSeF. */
    @Json(name = "token")
    val token: kotlin.String? = null

) {


}

