/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.IndirectPermissionsTargetIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Identyfikator podmiotu, w którego kontekście chcemy pośrednio nadać uprawnienia. W przypadku nadawania uprawnienia generalnego, pole to powinno mieć wartość null. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
 *
 * @param type Typ identyfikatora.
 * @param `value` Wartość identyfikatora. W przypadku typu AllPartners należy pozostawić puste. W pozostałych przypadkach pole jest wymagane.
 */


data class IndirectPermissionsTargetIdentifier (

    /* Typ identyfikatora. */
    @Json(name = "type")
    val type: IndirectPermissionsTargetIdentifierType,

    /* Wartość identyfikatora. W przypadku typu AllPartners należy pozostawić puste. W pozostałych przypadkach pole jest wymagane. */
    @Json(name = "value")
    val `value`: kotlin.String? = null

) {


}

