/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.IndirectPermissionType
import pl.com.codenow.ksefclient.models.IndirectPermissionsSubjectIdentifier
import pl.com.codenow.ksefclient.models.IndirectPermissionsTargetIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectIdentifier Identyfikator osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
 * @param permissions Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
 * @param description Opis nadawanych uprawnień.
 * @param targetIdentifier Identyfikator podmiotu, w którego kontekście chcemy pośrednio nadać uprawnienia. W przypadku nadawania uprawnienia generalnego, pole to powinno mieć wartość null. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
 */


data class IndirectPermissionsGrantRequest (

    /* Identyfikator osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: IndirectPermissionsSubjectIdentifier,

    /* Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz. */
    @Json(name = "permissions")
    val permissions: kotlin.collections.List<IndirectPermissionType>,

    /* Opis nadawanych uprawnień. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Identyfikator podmiotu, w którego kontekście chcemy pośrednio nadać uprawnienia. W przypadku nadawania uprawnienia generalnego, pole to powinno mieć wartość null. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego | */
    @Json(name = "targetIdentifier")
    val targetIdentifier: IndirectPermissionsTargetIdentifier? = null

) {


}

