/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.ThirdSubjectIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identifierType Typ identyfikatora podmiotu trzeciego. | Wartość | Opis | | --- | --- | | Nip | Nip | | InternalId | Identyfikator wewnętrzny | | VatUe | VAT UE | | Other | Inny identyfikator | | None | Brak identyfikatora podmiotu trzeciego | 
 * @param role Rola podmiotu trzeciego.
 * @param identifier Wartość identyfikatora podmiotu trzeciego.
 * @param name Nazwa podmiotu trzeciego.
 */


data class InvoiceMetadataThirdSubject (

    /* Typ identyfikatora podmiotu trzeciego. | Wartość | Opis | | --- | --- | | Nip | Nip | | InternalId | Identyfikator wewnętrzny | | VatUe | VAT UE | | Other | Inny identyfikator | | None | Brak identyfikatora podmiotu trzeciego |  */
    @Json(name = "identifierType")
    val identifierType: ThirdSubjectIdentifierType,

    /* Rola podmiotu trzeciego. */
    @Json(name = "role")
    val role: kotlin.Int,

    /* Wartość identyfikatora podmiotu trzeciego. */
    @Json(name = "identifier")
    val identifier: kotlin.String? = null,

    /* Nazwa podmiotu trzeciego. */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

