/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.InvoicePackage
import pl.com.codenow.ksefclient.models.StatusInfo

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Status eksportu.  | Code | Description | Details | | --- | --- | --- | | 100 | Eksport faktur w toku | - | | 200 | Eksport faktur zakończony sukcesem | - | | 415 | Błąd odszyfrowania dostarczonego klucza  | - | | 500 | Nieznany błąd ({statusCode}) | - |
 * @param completedDate Data zakończenia przetwarzania żądania.
 * @param `package` Dane paczki faktur przygotowanej do pobrania.
 */


data class InvoiceExportStatusResponse (

    /* Status eksportu.  | Code | Description | Details | | --- | --- | --- | | 100 | Eksport faktur w toku | - | | 200 | Eksport faktur zakończony sukcesem | - | | 415 | Błąd odszyfrowania dostarczonego klucza  | - | | 500 | Nieznany błąd ({statusCode}) | - | */
    @Json(name = "status")
    val status: StatusInfo,

    /* Data zakończenia przetwarzania żądania. */
    @Json(name = "completedDate")
    val completedDate: java.time.LocalDateTime? = null,

    /* Dane paczki faktur przygotowanej do pobrania. */
    @Json(name = "package")
    val `package`: InvoicePackage? = null

) {


}

