/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identifier Identyfikator sprzedawcy.
 * @param nip Nip sprzedawcy.
 */


data class InvoiceQuerySeller (

    /* Identyfikator sprzedawcy. */
    @Json(name = "identifier")
    @Deprecated(message = "This property is deprecated.")
    val identifier: kotlin.String? = null,

    /* Nip sprzedawcy. */
    @Json(name = "nip")
    val nip: kotlin.String? = null

) {


}

