/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.BuyerIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param identifierType Typ identyfikatora nabywcy. | Wartość | Opis | | --- | --- | | None | Brak identyfikatora nabywcy | | Other | Inny | | Nip | NIP | | VatUe | VAT UE | 
 * @param identifier Wartość identyfikatora nabywcy.
 */


data class InvoiceQueryBuyer (

    /* Typ identyfikatora nabywcy. | Wartość | Opis | | --- | --- | | None | Brak identyfikatora nabywcy | | Other | Inny | | Nip | NIP | | VatUe | VAT UE |  */
    @Json(name = "identifierType")
    val identifierType: BuyerIdentifierType? = null,

    /* Wartość identyfikatora nabywcy. */
    @Json(name = "identifier")
    val identifier: kotlin.String? = null

) {


}

