/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ordinalNumber Numer sekwencyjny pliku części paczki.
 * @param partName Nazwa pliku części paczki.
 * @param method Metoda HTTP, której należy użyć przy pobieraniu pliku.
 * @param url Adres URL, pod który należy wysłać żądanie pobrania.
 * @param partSize Rozmiar części paczki w bajtach. Maksymalny rozmiar części to 50MiB (52 428 800 bajtów).
 * @param partHash Skrót SHA256 pliku części paczki, zakodowany w formacie Base64.
 * @param encryptedPartSize Rozmiar zaszyfrowanej części paczki w bajtach.
 * @param encryptedPartHash Skrót SHA256 zaszyfrowanej części paczki, zakodowany w formacie Base64.
 * @param expirationDate Moment wygaśnięcia linku do pobrania części.
 */


data class InvoicePackagePart (

    /* Numer sekwencyjny pliku części paczki. */
    @Json(name = "ordinalNumber")
    val ordinalNumber: kotlin.Int,

    /* Nazwa pliku części paczki. */
    @Json(name = "partName")
    val partName: kotlin.String,

    /* Metoda HTTP, której należy użyć przy pobieraniu pliku. */
    @Json(name = "method")
    val method: kotlin.String,

    /* Adres URL, pod który należy wysłać żądanie pobrania. */
    @Json(name = "url")
    val url: java.net.URI,

    /* Rozmiar części paczki w bajtach. Maksymalny rozmiar części to 50MiB (52 428 800 bajtów). */
    @Json(name = "partSize")
    val partSize: kotlin.Long,

    /* Skrót SHA256 pliku części paczki, zakodowany w formacie Base64. */
    @Json(name = "partHash")
    val partHash: kotlin.String,

    /* Rozmiar zaszyfrowanej części paczki w bajtach. */
    @Json(name = "encryptedPartSize")
    val encryptedPartSize: kotlin.Long,

    /* Skrót SHA256 zaszyfrowanej części paczki, zakodowany w formacie Base64. */
    @Json(name = "encryptedPartHash")
    val encryptedPartHash: kotlin.String,

    /* Moment wygaśnięcia linku do pobrania części. */
    @Json(name = "expirationDate")
    val expirationDate: java.time.LocalDateTime

) {


}

