/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.AmountType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param from 
 * @param to 
 */


data class InvoiceQueryAmount (

    @Json(name = "type")
    val type: AmountType? = null,

    @Json(name = "from")
    val from: kotlin.Double? = null,

    @Json(name = "to")
    val to: kotlin.Double? = null

) {


}

