/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * | Wartość | Opis | | --- | --- | | Subject1 | Podmiot 1 | | Subject2 | Podmiot 2 | | Subject3 | Podmiot 3 | | SubjectAuthorized | Podmiot upoważniony | 
 *
 * Values: Subject1,Subject2,Subject3,SubjectAuthorized
 */

@JsonClass(generateAdapter = false)
enum class InvoiceQuerySubjectType(val value: kotlin.String) {

    @Json(name = "Subject1")
    Subject1("Subject1"),

    @Json(name = "Subject2")
    Subject2("Subject2"),

    @Json(name = "Subject3")
    Subject3("Subject3"),

    @Json(name = "SubjectAuthorized")
    SubjectAuthorized("SubjectAuthorized");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is InvoiceQuerySubjectType) "$data" else null

        /**
         * Returns a valid [InvoiceQuerySubjectType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): InvoiceQuerySubjectType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

