/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EncryptionInfo
import pl.com.codenow.ksefclient.models.InvoiceQueryFilters

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param encryption Informacje wymagane do zaszyfrowania wyniku zapytania.
 * @param filters Zestaw filtrów do wyszukiwania faktur.
 */


data class InvoiceExportRequest (

    /* Informacje wymagane do zaszyfrowania wyniku zapytania. */
    @Json(name = "encryption")
    val encryption: EncryptionInfo,

    /* Zestaw filtrów do wyszukiwania faktur. */
    @Json(name = "filters")
    val filters: InvoiceQueryFilters

) {


}

