/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline | 
 *
 * Values: Authentication,Offline
 */

@JsonClass(generateAdapter = false)
enum class KsefCertificateType(val value: kotlin.String) {

    @Json(name = "Authentication")
    Authentication("Authentication"),

    @Json(name = "Offline")
    Offline("Offline");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is KsefCertificateType) "$data" else null

        /**
         * Returns a valid [KsefCertificateType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): KsefCertificateType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

