/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.PartUploadRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny sesji.
 * @param partUploadRequests Dane wymagane do poprawnego przesłania poszczególnych części pliku paczki faktur.
 */


data class OpenBatchSessionResponse (

    /* Numer referencyjny sesji. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String,

    /* Dane wymagane do poprawnego przesłania poszczególnych części pliku paczki faktur. */
    @Json(name = "partUploadRequests")
    val partUploadRequests: kotlin.collections.List<PartUploadRequest>

) {


}

