/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny sesji.
 * @param validUntil Termin ważności sesji. Po jego upływie sesja zostanie automatycznie zamknięta.
 */


data class OpenOnlineSessionResponse (

    /* Numer referencyjny sesji. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String,

    /* Termin ważności sesji. Po jego upływie sesja zostanie automatycznie zamknięta. */
    @Json(name = "validUntil")
    val validUntil: java.time.LocalDateTime

) {


}

