/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EncryptionInfo
import pl.com.codenow.ksefclient.models.FormCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param formCode Schemat faktur wysyłanych w ramach sesji.  Obsługiwane schematy: | SystemCode | SchemaVersion | Value | | --- | --- | --- | | FA (2) | 1-0E | FA | | FA (3) | 1-0E | FA | | FA_PEF (3) | 2-1 | FA_PEF | | FA_KOR_PEF (3) | 2-1 | FA_PEF | 
 * @param encryption Symetryczny klucz szyfrujący pliki XML, zaszyfrowany kluczem publicznym Ministerstwa Finansów.
 */


data class OpenOnlineSessionRequest (

    /* Schemat faktur wysyłanych w ramach sesji.  Obsługiwane schematy: | SystemCode | SchemaVersion | Value | | --- | --- | --- | | FA (2) | 1-0E | FA | | FA (3) | 1-0E | FA | | FA_PEF (3) | 2-1 | FA_PEF | | FA_KOR_PEF (3) | 2-1 | FA_PEF |  */
    @Json(name = "formCode")
    val formCode: FormCode,

    /* Symetryczny klucz szyfrujący pliki XML, zaszyfrowany kluczem publicznym Ministerstwa Finansów. */
    @Json(name = "encryption")
    val encryption: EncryptionInfo

) {


}

