/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param ordinalNumber Numer sekwencyjny części pliku paczki.
 * @param method Metoda HTTP, której należy użyć przy wysyłce części pliku paczki.
 * @param url Adres pod który należy wysłać część pliku paczki.
 * @param headers Nagłówki, których należy użyć przy wysyłce części pliku paczki.
 */


data class PartUploadRequest (

    /* Numer sekwencyjny części pliku paczki. */
    @Json(name = "ordinalNumber")
    val ordinalNumber: kotlin.Int? = null,

    /* Metoda HTTP, której należy użyć przy wysyłce części pliku paczki. */
    @Json(name = "method")
    val method: kotlin.String? = null,

    /* Adres pod który należy wysłać część pliku paczki. */
    @Json(name = "url")
    val url: java.net.URI? = null,

    /* Nagłówki, których należy użyć przy wysyłce części pliku paczki. */
    @Json(name = "headers")
    val headers: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

