/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identyfikator dostawcy usług Peppol.
 * @param name Nazwa dostawcy usług Peppol.
 */


data class PeppolProvider (

    /* Identyfikator dostawcy usług Peppol. */
    @Json(name = "id")
    val id: kotlin.String? = null,

    /* Nazwa dostawcy usług Peppol. */
    @Json(name = "name")
    val name: kotlin.String? = null

) {


}

