/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param operationReferenceNumber Numer referencyjny asynchronicznej operacji nadawania lub odbierania uprawnień.
 */


data class PermissionsOperationResponse (

    /* Numer referencyjny asynchronicznej operacji nadawania lub odbierania uprawnień. */
    @Json(name = "operationReferenceNumber")
    val operationReferenceNumber: kotlin.String? = null

) {


}

