/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Identyfikator osoby lub podmiotu nadającego uprawnienie. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | | System | Identyfikator systemowy KSeF |
 *
 * @param type Typ identyfikatora.
 * @param `value` Wartość identyfikatora. W przypadku typu System należy pozostawić puste. W pozostałych przypadkach pole jest wymagane.
 */


data class PersonPermissionsAuthorIdentifier (

    /* Typ identyfikatora. */
    @Json(name = "type")
    val type: PersonPermissionsAuthorIdentifierType,

    /* Wartość identyfikatora. W przypadku typu System należy pozostawić puste. W pozostałych przypadkach pole jest wymagane. */
    @Json(name = "value")
    val `value`: kotlin.String? = null

) {


}

