/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.PermissionState
import pl.com.codenow.ksefclient.models.PersonPermissionType
import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorIdentifier
import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorizedIdentifier
import pl.com.codenow.ksefclient.models.PersonPermissionsQueryType
import pl.com.codenow.ksefclient.models.PersonPermissionsTargetIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param queryType Typ zapytania. | Type | Value | | --- | --- | | PermissionsInCurrentContext | Uprawnienia posiadane w aktualnym kontekście | | PermissionsGrantedInCurrentContext | Uprawnienia nadane w aktualnym kontekście |
 * @param authorIdentifier Identyfikator osoby lub podmiotu nadającego uprawnienie. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | | System | Identyfikator systemowy KSeF |
 * @param authorizedIdentifier Identyfikator osoby lub podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
 * @param targetIdentifier Identyfikator podmiotu docelowego (dla uprawnień pośrednich). | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
 * @param permissionTypes Możliwe uprawnienia do filtrowania.
 * @param permissionState Stan uprawnienia.  | Type | Value | | --- | --- | | Active | Uprawnienia aktywne | | Inactive | Uprawnienia nieaktywne, nadane w sposób poœredni |
 */


data class PersonPermissionsQueryRequest (

    /* Typ zapytania. | Type | Value | | --- | --- | | PermissionsInCurrentContext | Uprawnienia posiadane w aktualnym kontekście | | PermissionsGrantedInCurrentContext | Uprawnienia nadane w aktualnym kontekście | */
    @Json(name = "queryType")
    val queryType: PersonPermissionsQueryType,

    /* Identyfikator osoby lub podmiotu nadającego uprawnienie. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | | System | Identyfikator systemowy KSeF | */
    @Json(name = "authorIdentifier")
    val authorIdentifier: PersonPermissionsAuthorIdentifier? = null,

    /* Identyfikator osoby lub podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | */
    @Json(name = "authorizedIdentifier")
    val authorizedIdentifier: PersonPermissionsAuthorizedIdentifier? = null,

    /* Identyfikator podmiotu docelowego (dla uprawnień pośrednich). | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego | */
    @Json(name = "targetIdentifier")
    val targetIdentifier: PersonPermissionsTargetIdentifier? = null,

    /* Możliwe uprawnienia do filtrowania. */
    @Json(name = "permissionTypes")
    val permissionTypes: kotlin.collections.List<PersonPermissionType>? = null,

    /* Stan uprawnienia.  | Type | Value | | --- | --- | | Active | Uprawnienia aktywne | | Inactive | Uprawnienia nieaktywne, nadane w sposób poœredni | */
    @Json(name = "permissionState")
    val permissionState: PermissionState? = null

) {


}

