/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.PublicKeyCertificateUsage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param certificate Certyfikat klucza publicznego w formacie DER zakodowany w Base64.
 * @param validFrom Data początku obowiązywania certyfikatu.
 * @param validTo Data końca obowiązywania certyfikatu.
 * @param usage Operacje do których może być używany certyfikat. | Wartość | Opis | | --- | --- | | KsefTokenEncryption | Szyfrowanie tokenów KSeF przesyłanych w trakcie procesu uwierzytelniania. | | SymmetricKeyEncryption | Szyfrowanie klucza symetrycznego wykorzystywanego do szyfrowania przesyłanych faktur. | 
 */


data class PublicKeyCertificate (

    /* Certyfikat klucza publicznego w formacie DER zakodowany w Base64. */
    @Json(name = "certificate")
    val certificate: kotlin.String,

    /* Data początku obowiązywania certyfikatu. */
    @Json(name = "validFrom")
    val validFrom: java.time.LocalDateTime,

    /* Data końca obowiązywania certyfikatu. */
    @Json(name = "validTo")
    val validTo: java.time.LocalDateTime,

    /* Operacje do których może być używany certyfikat. | Wartość | Opis | | --- | --- | | KsefTokenEncryption | Szyfrowanie tokenów KSeF przesyłanych w trakcie procesu uwierzytelniania. | | SymmetricKeyEncryption | Szyfrowanie klucza symetrycznego wykorzystywanego do szyfrowania przesyłanych faktur. |  */
    @Json(name = "usage")
    val usage: kotlin.collections.List<PublicKeyCertificateUsage>

) {


}

