/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * | Wartość | Opis | | --- | --- | | KsefTokenEncryption | Szyfrowanie tokenów KSeF przesyłanych w trakcie procesu uwierzytelniania. | | SymmetricKeyEncryption | Szyfrowanie klucza symetrycznego wykorzystywanego do szyfrowania przesyłanych faktur. | 
 *
 * Values: KsefTokenEncryption,SymmetricKeyEncryption
 */

@JsonClass(generateAdapter = false)
enum class PublicKeyCertificateUsage(val value: kotlin.String) {

    @Json(name = "KsefTokenEncryption")
    KsefTokenEncryption("KsefTokenEncryption"),

    @Json(name = "SymmetricKeyEncryption")
    SymmetricKeyEncryption("SymmetricKeyEncryption");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PublicKeyCertificateUsage) "$data" else null

        /**
         * Returns a valid [PublicKeyCertificateUsage] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PublicKeyCertificateUsage? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

