/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.PeppolProvider

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param peppolProviders Lista dostawców usług Peppol.
 * @param hasMore Flaga informująca o dostępności kolejnej strony wyników.
 */


data class QueryPeppolProvidersResponse (

    /* Lista dostawców usług Peppol. */
    @Json(name = "peppolProviders")
    val peppolProviders: kotlin.collections.List<PeppolProvider>,

    /* Flaga informująca o dostępności kolejnej strony wyników. */
    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean

) {


}

