/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityRole

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param roles Lista ról.
 * @param hasMore Flaga informująca o dostępności kolejnej strony wyników.
 */


data class QueryEntityRolesResponse (

    /* Lista ról. */
    @Json(name = "roles")
    val roles: kotlin.collections.List<EntityRole>,

    /* Flaga informująca o dostępności kolejnej strony wyników. */
    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean

) {


}

