/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.CertificateListItem

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param certificates Lista certyfikatów spełniających kryteria wyszukiwania.
 * @param hasMore Flaga informująca o dostępności kolejnej strony wyników.
 */


data class QueryCertificatesResponse (

    /* Lista certyfikatów spełniających kryteria wyszukiwania. */
    @Json(name = "certificates")
    val certificates: kotlin.collections.List<CertificateListItem>,

    /* Flaga informująca o dostępności kolejnej strony wyników. */
    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean

) {


}

