/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityAuthorizationGrant

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param authorizationGrants Lista uprawnień.
 * @param hasMore Flaga informująca o dostępności kolejnej strony wyników.
 */


data class QueryEntityAuthorizationPermissionsResponse (

    /* Lista uprawnień. */
    @Json(name = "authorizationGrants")
    val authorizationGrants: kotlin.collections.List<EntityAuthorizationGrant>,

    /* Flaga informująca o dostępności kolejnej strony wyników. */
    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean

) {


}

