/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.AuthenticationToken

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param tokens Lista tokenów uwierzytelniających.
 * @param continuationToken Token służący do pobrania kolejnej strony wyników. Jeśli jest pusty, to nie ma kolejnych stron.
 */


data class QueryTokensResponse (

    /* Lista tokenów uwierzytelniających. */
    @Json(name = "tokens")
    val tokens: kotlin.collections.List<AuthenticationToken>,

    /* Token służący do pobrania kolejnej strony wyników. Jeśli jest pusty, to nie ma kolejnych stron. */
    @Json(name = "continuationToken")
    val continuationToken: kotlin.String? = null

) {


}

