/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param certificateSerialNumbers Numery seryjne certyfikatów do pobrania.
 */


data class RetrieveCertificatesRequest (

    /* Numery seryjne certyfikatów do pobrania. */
    @Json(name = "certificateSerialNumbers")
    val certificateSerialNumbers: kotlin.collections.List<kotlin.String>

) {


}

