/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invoiceHash Skrót SHA256 oryginalnej faktury, zakodowany w formacie Base64.
 * @param invoiceSize Rozmiar oryginalnej faktury w bajtach.
 * @param encryptedInvoiceHash Skrót SHA256 zaszyfrowanej faktury, zakodowany w formacie Base64.
 * @param encryptedInvoiceSize Rozmiar zaszyfrowanej faktury w bajtach.
 * @param encryptedInvoiceContent Faktura zaszyfrowana algorytmem AES-256-CBC z dopełnianiem PKCS#7 (kluczem przekazanym przy otwarciu sesji), zakodowana w formacie Base64.
 * @param offlineMode Określa, czy podatnik deklaruje tryb fakturowania \"offline\" dla przesyłanego dokumentu.
 * @param hashOfCorrectedInvoice Skrót SHA256 korygowanej faktury, zakodowany w formacie Base64. Wymagany przy wysyłaniu korekty technicznej faktury.
 */


data class SendInvoiceRequest (

    /* Skrót SHA256 oryginalnej faktury, zakodowany w formacie Base64. */
    @Json(name = "invoiceHash")
    val invoiceHash: kotlin.String,

    /* Rozmiar oryginalnej faktury w bajtach. */
    @Json(name = "invoiceSize")
    val invoiceSize: kotlin.Long,

    /* Skrót SHA256 zaszyfrowanej faktury, zakodowany w formacie Base64. */
    @Json(name = "encryptedInvoiceHash")
    val encryptedInvoiceHash: kotlin.String,

    /* Rozmiar zaszyfrowanej faktury w bajtach. */
    @Json(name = "encryptedInvoiceSize")
    val encryptedInvoiceSize: kotlin.Long,

    /* Faktura zaszyfrowana algorytmem AES-256-CBC z dopełnianiem PKCS#7 (kluczem przekazanym przy otwarciu sesji), zakodowana w formacie Base64. */
    @Json(name = "encryptedInvoiceContent")
    val encryptedInvoiceContent: kotlin.String,

    /* Określa, czy podatnik deklaruje tryb fakturowania \"offline\" dla przesyłanego dokumentu. */
    @Json(name = "offlineMode")
    val offlineMode: kotlin.Boolean? = false,

    /* Skrót SHA256 korygowanej faktury, zakodowany w formacie Base64. Wymagany przy wysyłaniu korekty technicznej faktury. */
    @Json(name = "hashOfCorrectedInvoice")
    val hashOfCorrectedInvoice: kotlin.String? = null

) {


}

