/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SessionInvoiceStatusResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param invoices Lista pobranych faktur.
 * @param continuationToken Token służący do pobrania kolejnej strony wyników. Jeśli jest pusty, to nie ma kolejnych stron.
 */


data class SessionInvoicesResponse (

    /* Lista pobranych faktur. */
    @Json(name = "invoices")
    val invoices: kotlin.collections.List<SessionInvoiceStatusResponse>,

    /* Token służący do pobrania kolejnej strony wyników. Jeśli jest pusty, to nie ma kolejnych stron. */
    @Json(name = "continuationToken")
    val continuationToken: kotlin.String? = null

) {


}

