/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.StatusInfo
import pl.com.codenow.ksefclient.models.UpoResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Informacje o aktualnym statusie.              Sesja wsadowa: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja wsadowa rozpoczęta | - | | 150 | Trwa przetwarzanie | - | | 200 | Sesja wsadowa przetworzona pomyślnie | - | | 405 | Błąd weryfikacji poprawności dostarczonych elementów paczki | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 430 | Błąd dekompresji pierwotnego archiwum | - | | 435 | Błąd odszyfrowania zaszyfrowanych części archiwum | - | | 440 | Sesja anulowana, przekroczono czas wysyłki | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | 500 | Nieznany błąd ({statusCode}) | - |  Sesja interaktywna: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja interaktywna otwarta | - | | 170 | Sesja interaktywna zamknięta | - | | 200 | Sesja interaktywna przetworzona pomyślnie | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 440 | Sesja anulowana, nie przesłano faktur | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | * | description missing | - |
 * @param validUntil Termin ważności sesji. Po jego upływie sesja zostanie automatycznie zamknięta.
 * @param upo Informacja o UPO sesyjnym, zwracana gdy sesja została zamknięta i UPO zostało wygenerowane.
 * @param invoiceCount Liczba przyjętych faktur w ramach sesji.
 * @param successfulInvoiceCount Liczba faktur przeprocesowanych w ramach sesji z sukcesem .
 * @param failedInvoiceCount Liczba faktur przeprocesowanych w ramach sesji z błędem.
 */


data class SessionStatusResponse (

    /* Informacje o aktualnym statusie.              Sesja wsadowa: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja wsadowa rozpoczęta | - | | 150 | Trwa przetwarzanie | - | | 200 | Sesja wsadowa przetworzona pomyślnie | - | | 405 | Błąd weryfikacji poprawności dostarczonych elementów paczki | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 430 | Błąd dekompresji pierwotnego archiwum | - | | 435 | Błąd odszyfrowania zaszyfrowanych części archiwum | - | | 440 | Sesja anulowana, przekroczono czas wysyłki | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | 500 | Nieznany błąd ({statusCode}) | - |  Sesja interaktywna: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja interaktywna otwarta | - | | 170 | Sesja interaktywna zamknięta | - | | 200 | Sesja interaktywna przetworzona pomyślnie | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 440 | Sesja anulowana, nie przesłano faktur | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | * | description missing | - | */
    @Json(name = "status")
    val status: StatusInfo,

    /* Termin ważności sesji. Po jego upływie sesja zostanie automatycznie zamknięta. */
    @Json(name = "validUntil")
    val validUntil: java.time.LocalDateTime? = null,

    /* Informacja o UPO sesyjnym, zwracana gdy sesja została zamknięta i UPO zostało wygenerowane. */
    @Json(name = "upo")
    val upo: UpoResponse? = null,

    /* Liczba przyjętych faktur w ramach sesji. */
    @Json(name = "invoiceCount")
    val invoiceCount: kotlin.Int? = null,

    /* Liczba faktur przeprocesowanych w ramach sesji z sukcesem . */
    @Json(name = "successfulInvoiceCount")
    val successfulInvoiceCount: kotlin.Int? = null,

    /* Liczba faktur przeprocesowanych w ramach sesji z błędem. */
    @Json(name = "failedInvoiceCount")
    val failedInvoiceCount: kotlin.Int? = null

) {


}

