/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: EnforcementAuthority,VatGroup,JST
 */

@JsonClass(generateAdapter = false)
enum class SubjectType(val value: kotlin.String) {

    @Json(name = "EnforcementAuthority")
    EnforcementAuthority("EnforcementAuthority"),

    @Json(name = "VatGroup")
    VatGroup("VatGroup"),

    @Json(name = "JST")
    JST("JST");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectType) "$data" else null

        /**
         * Returns a valid [SubjectType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

