/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SubjectType
import pl.com.codenow.ksefclient.models.Subunit

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectNip 
 * @param subjectType 
 * @param subunits 
 * @param description 
 * @param createdDate 
 */


data class SubjectCreateRequest (

    @Json(name = "subjectNip")
    val subjectNip: kotlin.String? = null,

    @Json(name = "subjectType")
    val subjectType: SubjectType? = null,

    @Json(name = "subunits")
    val subunits: kotlin.collections.List<Subunit>? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "createdDate")
    val createdDate: java.time.LocalDateTime? = null

) {


}

