/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: None,Nip,Pesel,Fingerprint,Token
 */

@JsonClass(generateAdapter = false)
enum class SubjectIdentifierType(val value: kotlin.String) {

    @Json(name = "None")
    None("None"),

    @Json(name = "Nip")
    Nip("Nip"),

    @Json(name = "Pesel")
    Pesel("Pesel"),

    @Json(name = "Fingerprint")
    Fingerprint("Fingerprint"),

    @Json(name = "Token")
    Token("Token");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SubjectIdentifierType) "$data" else null

        /**
         * Returns a valid [SubjectIdentifierType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SubjectIdentifierType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

