/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SubordinateEntityRoleType
import pl.com.codenow.ksefclient.models.SubordinateRoleSubordinateEntityIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subordinateEntityIdentifier Identyfikator podmiotu podrzędnego.
 * @param subordinateEntityIdentifierType Typ identyfikatora podmiotu podrzędnego.
 * @param role Powiązanie.
 * @param description Opis.
 * @param startDate Data rozpoczęcia obowiązywania powiązania.
 */


data class SubordinateEntityRole (

    /* Identyfikator podmiotu podrzędnego. */
    @Json(name = "subordinateEntityIdentifier")
    val subordinateEntityIdentifier: kotlin.String,

    /* Typ identyfikatora podmiotu podrzędnego. */
    @Json(name = "subordinateEntityIdentifierType")
    val subordinateEntityIdentifierType: SubordinateRoleSubordinateEntityIdentifierType,

    /* Powiązanie. */
    @Json(name = "role")
    val role: SubordinateEntityRoleType,

    /* Opis. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Data rozpoczęcia obowiązywania powiązania. */
    @Json(name = "startDate")
    val startDate: java.time.LocalDateTime

) {


}

