/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.EntityPermissionsSubordinateEntityIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subordinateEntityIdentifier Identyfikator podmiotu podrzędnego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
 */


data class SubordinateEntityRolesQueryRequest (

    /* Identyfikator podmiotu podrzędnego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | */
    @Json(name = "subordinateEntityIdentifier")
    val subordinateEntityIdentifier: EntityPermissionsSubordinateEntityIdentifier? = null

) {


}

