/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SubunitPermissionScope
import pl.com.codenow.ksefclient.models.SubunitPermissionsAuthorIdentifierType
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubjectIdentifierType
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubunitIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Identyfikator uprawnienia.
 * @param authorizedIdentifier Identyfikator uprawnionego.
 * @param authorizedIdentifierType Typ identyfikatora uprawnionego.
 * @param subunitIdentifier Identyfikator podmiotu podrzędnego.
 * @param subunitIdentifierType Typ identyfikatora podmiotu podrzędnego.
 * @param authorIdentifier Identyfikator uprawniającego.
 * @param authorIdentifierType Typ identyfikatora uprawniającego.
 * @param permissionScope Uprawnienie.
 * @param description Opis uprawnienia.
 * @param startDate Data rozpoczęcia obowiązywania uprawnienia.
 */


data class SubunitPermission (

    /* Identyfikator uprawnienia. */
    @Json(name = "id")
    val id: kotlin.String,

    /* Identyfikator uprawnionego. */
    @Json(name = "authorizedIdentifier")
    val authorizedIdentifier: kotlin.String,

    /* Typ identyfikatora uprawnionego. */
    @Json(name = "authorizedIdentifierType")
    val authorizedIdentifierType: SubunitPermissionsSubjectIdentifierType,

    /* Identyfikator podmiotu podrzędnego. */
    @Json(name = "subunitIdentifier")
    val subunitIdentifier: kotlin.String,

    /* Typ identyfikatora podmiotu podrzędnego. */
    @Json(name = "subunitIdentifierType")
    val subunitIdentifierType: SubunitPermissionsSubunitIdentifierType,

    /* Identyfikator uprawniającego. */
    @Json(name = "authorIdentifier")
    val authorIdentifier: kotlin.String,

    /* Typ identyfikatora uprawniającego. */
    @Json(name = "authorIdentifierType")
    val authorIdentifierType: SubunitPermissionsAuthorIdentifierType,

    /* Uprawnienie. */
    @Json(name = "permissionScope")
    val permissionScope: SubunitPermissionScope,

    /* Opis uprawnienia. */
    @Json(name = "description")
    val description: kotlin.String,

    /* Data rozpoczęcia obowiązywania uprawnienia. */
    @Json(name = "startDate")
    val startDate: java.time.LocalDateTime

) {


}

