/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SubunitPermissionsSubjectIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Identyfikator podmiotu lub osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
 *
 * @param type Typ identyfikatora.
 * @param `value` Wartość identyfikatora.
 */


data class SubunitPermissionsSubjectIdentifier (

    /* Typ identyfikatora. */
    @Json(name = "type")
    val type: SubunitPermissionsSubjectIdentifierType,

    /* Wartość identyfikatora. */
    @Json(name = "value")
    val `value`: kotlin.String

) {


}

