/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.SubunitPermissionsContextIdentifier
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubjectIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param subjectIdentifier Identyfikator podmiotu lub osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
 * @param contextIdentifier Identyfikator podmiotu podrzędnego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` |
 * @param description Opis nadawanych uprawnień.
 */


data class SubunitPermissionsGrantRequest (

    /* Identyfikator podmiotu lub osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | */
    @Json(name = "subjectIdentifier")
    val subjectIdentifier: SubunitPermissionsSubjectIdentifier,

    /* Identyfikator podmiotu podrzędnego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` | */
    @Json(name = "contextIdentifier")
    val contextIdentifier: SubunitPermissionsContextIdentifier,

    /* Opis nadawanych uprawnień. */
    @Json(name = "description")
    val description: kotlin.String

) {


}

