/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.TestDataAuthorizedIdentifier
import pl.com.codenow.ksefclient.models.TestDataContextIdentifier

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contextIdentifier 
 * @param authorizedIdentifier 
 */


data class TestDataPermissionsRevokeRequest (

    @Json(name = "contextIdentifier")
    val contextIdentifier: TestDataContextIdentifier? = null,

    @Json(name = "authorizedIdentifier")
    val authorizedIdentifier: TestDataAuthorizedIdentifier? = null

) {


}

