/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import pl.com.codenow.ksefclient.models.TestDataAuthorizedIdentifierType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param type 
 * @param `value` 
 */


data class TestDataAuthorizedIdentifier (

    @Json(name = "type")
    val type: TestDataAuthorizedIdentifierType? = null,

    @Json(name = "value")
    val `value`: kotlin.String? = null

) {


}

