/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param token Token w formacie JWT.
 * @param validUntil Data ważności tokena.
 */


data class TokenInfo (

    /* Token w formacie JWT. */
    @Json(name = "token")
    val token: kotlin.String,

    /* Data ważności tokena. */
    @Json(name = "validUntil")
    val validUntil: java.time.LocalDateTime

) {


}

