/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param referenceNumber Numer referencyjny strony UPO.
 * @param downloadUrl Adres do pobrania strony UPO.
 */


data class UpoPageResponse (

    /* Numer referencyjny strony UPO. */
    @Json(name = "referenceNumber")
    val referenceNumber: kotlin.String,

    /* Adres do pobrania strony UPO. */
    @Json(name = "downloadUrl")
    val downloadUrl: java.net.URI

) {


}

