/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.AktywneSesjeKsefApi
import pl.com.codenow.ksefclient.models.AuthenticationListResponse
import pl.com.codenow.ksefclient.models.ExceptionResponse

class AktywneSesjeKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AktywneSesjeKsefApi
        //val apiInstance = AktywneSesjeKsefApi()

        // to test apiV2AuthSessionsCurrentDelete
        should("test apiV2AuthSessionsCurrentDelete") {
            // uncomment below to test apiV2AuthSessionsCurrentDelete
            //apiInstance.apiV2AuthSessionsCurrentDelete()
        }

        // to test apiV2AuthSessionsGet
        should("test apiV2AuthSessionsGet") {
            // uncomment below to test apiV2AuthSessionsGet
            //val xContinuationToken : kotlin.String = xContinuationToken_example // kotlin.String | Token służący do pobrania kolejnej strony wyników.
            //val pageSize : kotlin.Int = 56 // kotlin.Int | Rozmiar strony wyników.
            //val result : AuthenticationListResponse = apiInstance.apiV2AuthSessionsGet(xContinuationToken, pageSize)
            //result shouldBe ("TODO")
        }

        // to test apiV2AuthSessionsReferenceNumberDelete
        should("test apiV2AuthSessionsReferenceNumberDelete") {
            // uncomment below to test apiV2AuthSessionsReferenceNumberDelete
            //val referenceNumber : kotlin.String = referenceNumber_example // kotlin.String | Numer referencyjny sesji uwierzytelnienia.
            //apiInstance.apiV2AuthSessionsReferenceNumberDelete(referenceNumber)
        }

    }
}
