/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.DaneTestoweKsefApi
import pl.com.codenow.ksefclient.models.AttachmentPermissionGrantRequest
import pl.com.codenow.ksefclient.models.AttachmentPermissionRevokeRequest
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.PersonCreateRequest
import pl.com.codenow.ksefclient.models.PersonRemoveRequest
import pl.com.codenow.ksefclient.models.SubjectCreateRequest
import pl.com.codenow.ksefclient.models.SubjectRemoveRequest
import pl.com.codenow.ksefclient.models.TestDataPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.TestDataPermissionsRevokeRequest

class DaneTestoweKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DaneTestoweKsefApi
        //val apiInstance = DaneTestoweKsefApi()

        // to test apiV2TestdataAttachmentPost
        should("test apiV2TestdataAttachmentPost") {
            // uncomment below to test apiV2TestdataAttachmentPost
            //val attachmentPermissionGrantRequest : AttachmentPermissionGrantRequest =  // AttachmentPermissionGrantRequest | 
            //apiInstance.apiV2TestdataAttachmentPost(attachmentPermissionGrantRequest)
        }

        // to test apiV2TestdataAttachmentRevokePost
        should("test apiV2TestdataAttachmentRevokePost") {
            // uncomment below to test apiV2TestdataAttachmentRevokePost
            //val attachmentPermissionRevokeRequest : AttachmentPermissionRevokeRequest =  // AttachmentPermissionRevokeRequest | 
            //apiInstance.apiV2TestdataAttachmentRevokePost(attachmentPermissionRevokeRequest)
        }

        // to test apiV2TestdataPermissionsPost
        should("test apiV2TestdataPermissionsPost") {
            // uncomment below to test apiV2TestdataPermissionsPost
            //val testDataPermissionsGrantRequest : TestDataPermissionsGrantRequest =  // TestDataPermissionsGrantRequest | 
            //apiInstance.apiV2TestdataPermissionsPost(testDataPermissionsGrantRequest)
        }

        // to test apiV2TestdataPermissionsRevokePost
        should("test apiV2TestdataPermissionsRevokePost") {
            // uncomment below to test apiV2TestdataPermissionsRevokePost
            //val testDataPermissionsRevokeRequest : TestDataPermissionsRevokeRequest =  // TestDataPermissionsRevokeRequest | 
            //apiInstance.apiV2TestdataPermissionsRevokePost(testDataPermissionsRevokeRequest)
        }

        // to test apiV2TestdataPersonPost
        should("test apiV2TestdataPersonPost") {
            // uncomment below to test apiV2TestdataPersonPost
            //val personCreateRequest : PersonCreateRequest =  // PersonCreateRequest | 
            //apiInstance.apiV2TestdataPersonPost(personCreateRequest)
        }

        // to test apiV2TestdataPersonRemovePost
        should("test apiV2TestdataPersonRemovePost") {
            // uncomment below to test apiV2TestdataPersonRemovePost
            //val personRemoveRequest : PersonRemoveRequest =  // PersonRemoveRequest | 
            //apiInstance.apiV2TestdataPersonRemovePost(personRemoveRequest)
        }

        // to test apiV2TestdataSubjectPost
        should("test apiV2TestdataSubjectPost") {
            // uncomment below to test apiV2TestdataSubjectPost
            //val subjectCreateRequest : SubjectCreateRequest =  // SubjectCreateRequest | 
            //apiInstance.apiV2TestdataSubjectPost(subjectCreateRequest)
        }

        // to test apiV2TestdataSubjectRemovePost
        should("test apiV2TestdataSubjectRemovePost") {
            // uncomment below to test apiV2TestdataSubjectRemovePost
            //val subjectRemoveRequest : SubjectRemoveRequest =  // SubjectRemoveRequest | 
            //apiInstance.apiV2TestdataSubjectRemovePost(subjectRemoveRequest)
        }

    }
}
