/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.NadawanieUprawnieKsefApi
import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.EntityPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.EuEntityAdministrationPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.EuEntityPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.IndirectPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.PermissionsOperationResponse
import pl.com.codenow.ksefclient.models.PersonPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.SubunitPermissionsGrantRequest

class NadawanieUprawnieKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NadawanieUprawnieKsefApi
        //val apiInstance = NadawanieUprawnieKsefApi()

        // to test apiV2PermissionsAuthorizationsGrantsPost
        should("test apiV2PermissionsAuthorizationsGrantsPost") {
            // uncomment below to test apiV2PermissionsAuthorizationsGrantsPost
            //val entityAuthorizationPermissionsGrantRequest : EntityAuthorizationPermissionsGrantRequest = {"subjectIdentifier":{"type":"Nip","value":"7762811692"},"permission":"SelfInvoicing","description":"Uprawnienia do samofakturowania"} // EntityAuthorizationPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsAuthorizationsGrantsPost(entityAuthorizationPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsEntitiesGrantsPost
        should("test apiV2PermissionsEntitiesGrantsPost") {
            // uncomment below to test apiV2PermissionsEntitiesGrantsPost
            //val entityPermissionsGrantRequest : EntityPermissionsGrantRequest = {"subjectIdentifier":{"type":"Nip","value":"7762811692"},"permissions":[{"type":"InvoiceRead","canDelegate":true},{"type":"InvoiceWrite","canDelegate":true}],"description":"Uprawnienia do odczytu i wysyłania faktur z możliwością nadania ich pośrednio"} // EntityPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsEntitiesGrantsPost(entityPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsEuEntitiesAdministrationGrantsPost
        should("test apiV2PermissionsEuEntitiesAdministrationGrantsPost") {
            // uncomment below to test apiV2PermissionsEuEntitiesAdministrationGrantsPost
            //val euEntityAdministrationPermissionsGrantRequest : EuEntityAdministrationPermissionsGrantRequest = {"subjectIdentifier":{"type":"Fingerprint","value":"CEB3643BAC2C111ADDE971BDA5A80163441867D65389FC0BC0DFF8B4C1CD4E59"},"contextIdentifier":{"type":"NipVatUe","value":"7762811692-DE123456789012"},"description":"Administrator podmiotu unijnego DE123456789012"} // EuEntityAdministrationPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsEuEntitiesAdministrationGrantsPost(euEntityAdministrationPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsEuEntitiesGrantsPost
        should("test apiV2PermissionsEuEntitiesGrantsPost") {
            // uncomment below to test apiV2PermissionsEuEntitiesGrantsPost
            //val euEntityPermissionsGrantRequest : EuEntityPermissionsGrantRequest = {"subjectIdentifier":{"type":"Fingerprint","value":"CEB3643BAC2C111ADDE971BDA5A80163441867D65389FC0BC0DFF8B4C1CD4E59"},"permissions":["InvoiceRead","InvoiceWrite"],"description":"Reprezentant podmiotu unijnego"} // EuEntityPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsEuEntitiesGrantsPost(euEntityPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsIndirectGrantsPost
        should("test apiV2PermissionsIndirectGrantsPost") {
            // uncomment below to test apiV2PermissionsIndirectGrantsPost
            //val indirectPermissionsGrantRequest : IndirectPermissionsGrantRequest = {"subjectIdentifier":{"type":"Pesel","value":"15062788702"},"permissions":["InvoiceWrite","InvoiceRead"],"description":"Uprawnienia generalne do odczytu i wysyłania faktur, nadane w sposób pośredni"} // IndirectPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsIndirectGrantsPost(indirectPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsPersonsGrantsPost
        should("test apiV2PermissionsPersonsGrantsPost") {
            // uncomment below to test apiV2PermissionsPersonsGrantsPost
            //val personPermissionsGrantRequest : PersonPermissionsGrantRequest = {"subjectIdentifier":{"type":"Pesel","value":"15062788702"},"permissions":["InvoiceRead","InvoiceWrite"],"description":"Uprawnienia do odczytu i wysyłania faktur"} // PersonPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsPersonsGrantsPost(personPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsSubunitsGrantsPost
        should("test apiV2PermissionsSubunitsGrantsPost") {
            // uncomment below to test apiV2PermissionsSubunitsGrantsPost
            //val subunitPermissionsGrantRequest : SubunitPermissionsGrantRequest = {"subjectIdentifier":{"type":"Pesel","value":"15062788702"},"contextIdentifier":{"type":"InternalId","value":"7762811692-11111"},"description":"Administrator jednostki podrzędnej"} // SubunitPermissionsGrantRequest | 
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsSubunitsGrantsPost(subunitPermissionsGrantRequest)
            //result shouldBe ("TODO")
        }

    }
}
