/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.OdbieranieUprawnieKsefApi
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.PermissionsOperationResponse

class OdbieranieUprawnieKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OdbieranieUprawnieKsefApi
        //val apiInstance = OdbieranieUprawnieKsefApi()

        // to test apiV2PermissionsAuthorizationsGrantsPermissionIdDelete
        should("test apiV2PermissionsAuthorizationsGrantsPermissionIdDelete") {
            // uncomment below to test apiV2PermissionsAuthorizationsGrantsPermissionIdDelete
            //val permissionId : kotlin.String = permissionId_example // kotlin.String | Id uprawnienia.
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsAuthorizationsGrantsPermissionIdDelete(permissionId)
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsCommonGrantsPermissionIdDelete
        should("test apiV2PermissionsCommonGrantsPermissionIdDelete") {
            // uncomment below to test apiV2PermissionsCommonGrantsPermissionIdDelete
            //val permissionId : kotlin.String = permissionId_example // kotlin.String | Id uprawnienia.
            //val result : PermissionsOperationResponse = apiInstance.apiV2PermissionsCommonGrantsPermissionIdDelete(permissionId)
            //result shouldBe ("TODO")
        }

    }
}
