/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.OperacjeKsefApi
import pl.com.codenow.ksefclient.models.CheckAttachmentPermissionStatusResponse
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.PermissionsOperationStatusResponse

class OperacjeKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OperacjeKsefApi
        //val apiInstance = OperacjeKsefApi()

        // to test apiV2PermissionsAttachmentsStatusGet
        should("test apiV2PermissionsAttachmentsStatusGet") {
            // uncomment below to test apiV2PermissionsAttachmentsStatusGet
            //val result : CheckAttachmentPermissionStatusResponse = apiInstance.apiV2PermissionsAttachmentsStatusGet()
            //result shouldBe ("TODO")
        }

        // to test apiV2PermissionsOperationsOperationReferenceNumberGet
        should("test apiV2PermissionsOperationsOperationReferenceNumberGet") {
            // uncomment below to test apiV2PermissionsOperationsOperationReferenceNumberGet
            //val operationReferenceNumber : kotlin.String = operationReferenceNumber_example // kotlin.String | Numer referencyjny operacji
            //val result : PermissionsOperationStatusResponse = apiInstance.apiV2PermissionsOperationsOperationReferenceNumberGet(operationReferenceNumber)
            //result shouldBe ("TODO")
        }

    }
}
