/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.PobieranieFakturKsefApi
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.ExportInvoicesResponse
import pl.com.codenow.ksefclient.models.InvoiceExportRequest
import pl.com.codenow.ksefclient.models.InvoiceExportStatusResponse
import pl.com.codenow.ksefclient.models.InvoiceQueryFilters
import pl.com.codenow.ksefclient.models.QueryInvoicesMetadataResponse

class PobieranieFakturKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PobieranieFakturKsefApi
        //val apiInstance = PobieranieFakturKsefApi()

        // to test apiV2InvoicesExportsOperationReferenceNumberGet
        should("test apiV2InvoicesExportsOperationReferenceNumberGet") {
            // uncomment below to test apiV2InvoicesExportsOperationReferenceNumberGet
            //val operationReferenceNumber : kotlin.String = operationReferenceNumber_example // kotlin.String | Numer referencyjny operacji.
            //val result : InvoiceExportStatusResponse = apiInstance.apiV2InvoicesExportsOperationReferenceNumberGet(operationReferenceNumber)
            //result shouldBe ("TODO")
        }

        // to test apiV2InvoicesExportsPost
        should("test apiV2InvoicesExportsPost") {
            // uncomment below to test apiV2InvoicesExportsPost
            //val invoiceExportRequest : InvoiceExportRequest =  // InvoiceExportRequest | Dane wejściowe określające kryteria i format eksportu paczki faktur.
            //val result : ExportInvoicesResponse = apiInstance.apiV2InvoicesExportsPost(invoiceExportRequest)
            //result shouldBe ("TODO")
        }

        // to test apiV2InvoicesKsefKsefNumberGet
        should("test apiV2InvoicesKsefKsefNumberGet") {
            // uncomment below to test apiV2InvoicesKsefKsefNumberGet
            //val ksefNumber : kotlin.String = ksefNumber_example // kotlin.String | Numer KSeF faktury.
            //val result : kotlin.String = apiInstance.apiV2InvoicesKsefKsefNumberGet(ksefNumber)
            //result shouldBe ("TODO")
        }

        // to test apiV2InvoicesQueryMetadataPost
        should("test apiV2InvoicesQueryMetadataPost") {
            // uncomment below to test apiV2InvoicesQueryMetadataPost
            //val pageOffset : kotlin.Int = 56 // kotlin.Int | Indeks pierwszej strony wyników (0 = pierwsza strona).
            //val pageSize : kotlin.Int = 56 // kotlin.Int | Rozmiar strony wyników. Wartość musi zawierać się w przedziale od 10 do 250.
            //val invoiceQueryFilters : InvoiceQueryFilters =  // InvoiceQueryFilters | Zestaw filtrów dla wyszukiwania metadanych.
            //val result : QueryInvoicesMetadataResponse = apiInstance.apiV2InvoicesQueryMetadataPost(pageOffset, pageSize, invoiceQueryFilters)
            //result shouldBe ("TODO")
        }

    }
}
