/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.apis.WysykaInteraktywnaKsefApi
import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.OpenOnlineSessionRequest
import pl.com.codenow.ksefclient.models.OpenOnlineSessionResponse
import pl.com.codenow.ksefclient.models.SendInvoiceRequest
import pl.com.codenow.ksefclient.models.SendInvoiceResponse

class WysykaInteraktywnaKsefApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WysykaInteraktywnaKsefApi
        //val apiInstance = WysykaInteraktywnaKsefApi()

        // to test apiV2SessionsOnlineReferenceNumberClosePost
        should("test apiV2SessionsOnlineReferenceNumberClosePost") {
            // uncomment below to test apiV2SessionsOnlineReferenceNumberClosePost
            //val referenceNumber : kotlin.String = referenceNumber_example // kotlin.String | Numer referencyjny sesji
            //apiInstance.apiV2SessionsOnlineReferenceNumberClosePost(referenceNumber)
        }

        // to test apiV2SessionsOnlineReferenceNumberInvoicesPost
        should("test apiV2SessionsOnlineReferenceNumberInvoicesPost") {
            // uncomment below to test apiV2SessionsOnlineReferenceNumberInvoicesPost
            //val referenceNumber : kotlin.String = referenceNumber_example // kotlin.String | Numer referencyjny sesji
            //val sendInvoiceRequest : SendInvoiceRequest = {"invoiceHash":"EbrK4cOSjW4hEpJaHU71YXSOZZmqP5++dK9nLgTzgV4=","invoiceSize":6480,"encryptedInvoiceHash":"miYb1z3Ljw5VucTZslv3Tlt+V/EK1V8Q8evD8HMQ0dc=","encryptedInvoiceSize":6496,"encryptedInvoiceContent":"...","offlineMode":false} // SendInvoiceRequest | Dane faktury
            //val result : SendInvoiceResponse = apiInstance.apiV2SessionsOnlineReferenceNumberInvoicesPost(referenceNumber, sendInvoiceRequest)
            //result shouldBe ("TODO")
        }

        // to test onlineSessionOpen
        should("test onlineSessionOpen") {
            // uncomment below to test onlineSessionOpen
            //val openOnlineSessionRequest : OpenOnlineSessionRequest = {"formCode":{"systemCode":"FA (3)","schemaVersion":"1-0E","value":"FA"},"encryption":{"encryptedSymmetricKey":"bdUVjqLj+y2q6aBUuLxxXYAMqeDuIBRTyr+hB96DaWKaGzuVHw9p+Nk9vhzgF/Q5cavK2k6eCh6SdsrWI0s9mFFj4A4UJtsyD8Dn3esLfUZ5A1juuG3q3SBi/XOC/+9W+0T/KdwdE393mbiUNyx1K/0bw31vKJL0COeJIDP7usAMDl42/H1TNvkjk+8iZ80V0qW7D+RZdz+tdiY1xV0f2mfgwJ46V0CpZ+sB9UAssRj+eVffavJ0TOg2b5JaBxE8MCAvrF6rO5K4KBjUmoy7PP7g1qIbm8xI2GO0KnfPOO5OWj8rsotRwBgu7x19Ine3qYUvuvCZlXRGGZ5NHIzWPM4O74+gNalaMgFCsmv8mMhETSU4SfAGmJr9edxPjQSbgD5i2X4eDRDMwvyaAa7CP1b2oICju+0L7Fywd2ZtUcr6El++eTVoi8HYsTArntET++gULT7XXjmb8e3O0nxrYiYsE9GMJ7HBGv3NOoJ1NTm3a7U6+c0ZJiBVLvn6xXw10LQX243xH+ehsKo6djQJKYtqcNPaXtCwM1c9RrsOx/wRXyWCtTffqLiaR0LbYvfMJAcEWceG+RaeAx4p37OiQqdJypd6LAv9/0ECWK8Bip8yyoA+0EYiAJb9YuDz2YlQX9Mx9E9FzFIAsgEQ2w723HZYWgPywLb+dlsum4lTZKQ=","initializationVector":"OmtDQdl6vkOI1GLKZSjgEg=="}} // OpenOnlineSessionRequest | 
            //val result : OpenOnlineSessionResponse = apiInstance.onlineSessionOpen(openOnlineSessionRequest)
            //result shouldBe ("TODO")
        }

    }
}
