/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AttachmentPermissionGrantRequest

class AttachmentPermissionGrantRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AttachmentPermissionGrantRequest
        //val modelInstance = AttachmentPermissionGrantRequest()

        // to test the property `nip`
        should("test nip") {
            // uncomment below to test the property
            //modelInstance.nip shouldBe ("TODO")
        }

    }
}
