/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AuthenticationChallengeResponse

class AuthenticationChallengeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationChallengeResponse
        //val modelInstance = AuthenticationChallengeResponse()

        // to test the property `challenge` - Unikalny challenge.
        should("test challenge") {
            // uncomment below to test the property
            //modelInstance.challenge shouldBe ("TODO")
        }

        // to test the property `timestamp` - Czas wygenerowania challenge-a.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
