/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AuthorizationPolicy
import pl.com.codenow.ksefclient.models.AllowedIps

class AuthorizationPolicyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthorizationPolicy
        //val modelInstance = AuthorizationPolicy()

        // to test the property `allowedIps` - Lista dozwolonych adresów IP.
        should("test allowedIps") {
            // uncomment below to test the property
            //modelInstance.allowedIps shouldBe ("TODO")
        }

    }
}
