/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AuthenticationInitResponse
import pl.com.codenow.ksefclient.models.TokenInfo

class AuthenticationInitResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationInitResponse
        //val modelInstance = AuthenticationInitResponse()

        // to test the property `referenceNumber` - Numer referencyjny operacji uwierzytelnienia.
        should("test referenceNumber") {
            // uncomment below to test the property
            //modelInstance.referenceNumber shouldBe ("TODO")
        }

        // to test the property `authenticationToken` - Token operacji uwierzytelnienia.
        should("test authenticationToken") {
            // uncomment below to test the property
            //modelInstance.authenticationToken shouldBe ("TODO")
        }

    }
}
