/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AuthenticationToken
import pl.com.codenow.ksefclient.models.AuthenticationTokenStatus
import pl.com.codenow.ksefclient.models.ContextIdentifier
import pl.com.codenow.ksefclient.models.SubjectIdentifier
import pl.com.codenow.ksefclient.models.TokenPermissionType

class AuthenticationTokenTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationToken
        //val modelInstance = AuthenticationToken()

        // to test the property `referenceNumber` - Numer referencyjny tokena.
        should("test referenceNumber") {
            // uncomment below to test the property
            //modelInstance.referenceNumber shouldBe ("TODO")
        }

        // to test the property `authorIdentifier` - Identyfikator osoby która wygenerowała token.
        should("test authorIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorIdentifier shouldBe ("TODO")
        }

        // to test the property `contextIdentifier` - Identyfikator kontekstu, w którym został wygenerowany token i do którego daje dostęp.
        should("test contextIdentifier") {
            // uncomment below to test the property
            //modelInstance.contextIdentifier shouldBe ("TODO")
        }

        // to test the property `description` - Opis tokena.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `requestedPermissions` - Uprawnienia przypisane tokenowi.
        should("test requestedPermissions") {
            // uncomment below to test the property
            //modelInstance.requestedPermissions shouldBe ("TODO")
        }

        // to test the property `dateCreated` - Data i czas utworzenia tokena.
        should("test dateCreated") {
            // uncomment below to test the property
            //modelInstance.dateCreated shouldBe ("TODO")
        }

        // to test the property `lastUseDate` - Data ostatniego użycia tokena.
        should("test lastUseDate") {
            // uncomment below to test the property
            //modelInstance.lastUseDate shouldBe ("TODO")
        }

        // to test the property `status` - Status tokena. | Wartość | Opis | | --- | --- | | Pending | Token został utworzony ale jest jeszcze w trakcie aktywacji i nadawania uprawnień. Nie może być jeszcze wykorzystywany do uwierzytelniania. | | Active | Token jest aktywny i może być wykorzystywany do uwierzytelniania. | | Revoking | Token jest w trakcie unieważniania. Nie może już być wykorzystywany do uwierzytelniania. | | Revoked | Token został unieważniony i nie może być wykorzystywany do uwierzytelniania. | | Failed | Nie udało się aktywować tokena. Należy wygenerować nowy token, obecny nie może być wykorzystywany do uwierzytelniania. | 
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `statusDetails` - Dodatkowe informacje na temat statusu, zwracane w przypadku błędów.
        should("test statusDetails") {
            // uncomment below to test the property
            //modelInstance.statusDetails shouldBe ("TODO")
        }

    }
}
