/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.AuthenticationTokensResponse
import pl.com.codenow.ksefclient.models.TokenInfo

class AuthenticationTokensResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AuthenticationTokensResponse
        //val modelInstance = AuthenticationTokensResponse()

        // to test the property `accessToken` - Token dostępu.
        should("test accessToken") {
            // uncomment below to test the property
            //modelInstance.accessToken shouldBe ("TODO")
        }

        // to test the property `refreshToken` - Token umożliwiający odświeżenie tokenu dostępu. > Więcej informacji: > - [Odświeżanie tokena](https://github.com/CIRFMF/ksef-docs/blob/main/uwierzytelnianie.md#od%C5%9Bwie%C5%BCenie-tokena-accesstoken)
        should("test refreshToken") {
            // uncomment below to test the property
            //modelInstance.refreshToken shouldBe ("TODO")
        }

    }
}
