/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.CertificateEnrollmentStatusResponse
import pl.com.codenow.ksefclient.models.StatusInfo

class CertificateEnrollmentStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CertificateEnrollmentStatusResponse
        //val modelInstance = CertificateEnrollmentStatusResponse()

        // to test the property `requestDate` - Data złożenia wniosku certyfikacyjnego.
        should("test requestDate") {
            // uncomment below to test the property
            //modelInstance.requestDate shouldBe ("TODO")
        }

        // to test the property `status` - Informacje o aktualnym statusie. | Code | Description | Details | | --- | --- | --- | | 100 | Wniosek przyjęty do realizacji | - | | 200 | Wniosek obsłużony (certyfikat wygenerowany) | - | | 400 | Wniosek odrzucony | Klucz publiczny został już certyfikowany przez inny podmiot. | | 400 | Wniosek odrzucony | Osiągnięto dopuszczalny limit posiadanych certyfikatów. | | 500 | Nieznany błąd | - |
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `certificateSerialNumber` - Numer seryjny wygenerowanego certyfikatu (w formacie szesnastkowym).  Zwracany w przypadku prawidłowego przeprocesowania wniosku certyfikacyjnego.
        should("test certificateSerialNumber") {
            // uncomment below to test the property
            //modelInstance.certificateSerialNumber shouldBe ("TODO")
        }

    }
}
