/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.CertificateLimit

class CertificateLimitTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CertificateLimit
        //val modelInstance = CertificateLimit()

        // to test the property `remaining` - Pozostała wartość limitu.
        should("test remaining") {
            // uncomment below to test the property
            //modelInstance.remaining shouldBe ("TODO")
        }

        // to test the property `limit` - Maksymalna liczba zasobów dozwolona w ramach limitu.
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

    }
}
