/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.CertificateLimitsResponse
import pl.com.codenow.ksefclient.models.CertificateLimit

class CertificateLimitsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CertificateLimitsResponse
        //val modelInstance = CertificateLimitsResponse()

        // to test the property `canRequest` - Flaga informująca czy uwierzytelniony podmiot może złożyć nowy wniosek o certyfikat.
        should("test canRequest") {
            // uncomment below to test the property
            //modelInstance.canRequest shouldBe ("TODO")
        }

        // to test the property `enrollment` - Informacje o limitach związanych z liczbą możliwych do złożenia wniosków certyfikacyjnych.
        should("test enrollment") {
            // uncomment below to test the property
            //modelInstance.enrollment shouldBe ("TODO")
        }

        // to test the property `certificate` - Informacje o limitach dotyczących liczby aktywnych certyfikatów wydanych dla danego podmiotu.
        should("test certificate") {
            // uncomment below to test the property
            //modelInstance.certificate shouldBe ("TODO")
        }

    }
}
