/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.CheckAttachmentPermissionStatusResponse

class CheckAttachmentPermissionStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CheckAttachmentPermissionStatusResponse
        //val modelInstance = CheckAttachmentPermissionStatusResponse()

        // to test the property `isAttachmentAllowed` - Informacja czy Podmiot ma obecnie możliwość dodawania Załączników do Faktur
        should("test isAttachmentAllowed") {
            // uncomment below to test the property
            //modelInstance.isAttachmentAllowed shouldBe ("TODO")
        }

        // to test the property `revokedDate` - Data i czas zakończenia możliwość dodawania przez Podmiot Załączników do Faktur. Brak podanej daty oznacza bezterminową możliwość dodawania Załączników do Faktur
        should("test revokedDate") {
            // uncomment below to test the property
            //modelInstance.revokedDate shouldBe ("TODO")
        }

    }
}
