/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.EnrollCertificateResponse

class EnrollCertificateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EnrollCertificateResponse
        //val modelInstance = EnrollCertificateResponse()

        // to test the property `referenceNumber` - Numer referencyjny operacji przetwarzania wniosku certyfikacyjnego.
        should("test referenceNumber") {
            // uncomment below to test the property
            //modelInstance.referenceNumber shouldBe ("TODO")
        }

        // to test the property `timestamp` - Data złożenia wniosku certyfikacyjnego.
        should("test timestamp") {
            // uncomment below to test the property
            //modelInstance.timestamp shouldBe ("TODO")
        }

    }
}
