/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.EntityRole
import pl.com.codenow.ksefclient.models.EntityRoleType
import pl.com.codenow.ksefclient.models.EntityRolesParentEntityIdentifierType

class EntityRoleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntityRole
        //val modelInstance = EntityRole()

        // to test the property `role` - Rola.
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `description` - Opis.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `startDate` - Data rozpoczęcia obowiązywania roli.
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

        // to test the property `parentEntityIdentifier` - Identyfikator podmiotu nadrzędnego.
        should("test parentEntityIdentifier") {
            // uncomment below to test the property
            //modelInstance.parentEntityIdentifier shouldBe ("TODO")
        }

        // to test the property `parentEntityIdentifierType` - Typ identyfikatora podmiotu nadrzędnego.
        should("test parentEntityIdentifierType") {
            // uncomment below to test the property
            //modelInstance.parentEntityIdentifierType shouldBe ("TODO")
        }

    }
}
