/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionType
import pl.com.codenow.ksefclient.models.EntityAuthorizationPermissionsSubjectIdentifier

class EntityAuthorizationPermissionsGrantRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntityAuthorizationPermissionsGrantRequest
        //val modelInstance = EntityAuthorizationPermissionsGrantRequest()

        // to test the property `subjectIdentifier` - Identyfikator podmiotu. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP |
        should("test subjectIdentifier") {
            // uncomment below to test the property
            //modelInstance.subjectIdentifier shouldBe ("TODO")
        }

        // to test the property `permission` - Nadawane uprawnienie o charakterze upoważnienia.
        should("test permission") {
            // uncomment below to test the property
            //modelInstance.permission shouldBe ("TODO")
        }

        // to test the property `description` - Opis nadawanego uprawnienia.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
