/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.EuEntityPermissionsQueryRequest
import pl.com.codenow.ksefclient.models.EuEntityPermissionsQueryPermissionType

class EuEntityPermissionsQueryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EuEntityPermissionsQueryRequest
        //val modelInstance = EuEntityPermissionsQueryRequest()

        // to test the property `vatUeIdentifier` - Identyfikator podmiotu unijnego.
        should("test vatUeIdentifier") {
            // uncomment below to test the property
            //modelInstance.vatUeIdentifier shouldBe ("TODO")
        }

        // to test the property `authorizedFingerprintIdentifier` - Uprawniony odcisk palca certyfikatu.
        should("test authorizedFingerprintIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorizedFingerprintIdentifier shouldBe ("TODO")
        }

        // to test the property `permissionTypes` - Możliwe uprawnienia do filtrowania.
        should("test permissionTypes") {
            // uncomment below to test the property
            //modelInstance.permissionTypes shouldBe ("TODO")
        }

    }
}
