/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.ExceptionDetails

class ExceptionDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExceptionDetails
        //val modelInstance = ExceptionDetails()

        // to test the property `exceptionCode`
        should("test exceptionCode") {
            // uncomment below to test the property
            //modelInstance.exceptionCode shouldBe ("TODO")
        }

        // to test the property `exceptionDescription`
        should("test exceptionDescription") {
            // uncomment below to test the property
            //modelInstance.exceptionDescription shouldBe ("TODO")
        }

        // to test the property `details`
        should("test details") {
            // uncomment below to test the property
            //modelInstance.details shouldBe ("TODO")
        }

    }
}
