/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.ExceptionResponse
import pl.com.codenow.ksefclient.models.ExceptionInfo

class ExceptionResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExceptionResponse
        //val modelInstance = ExceptionResponse()

        // to test the property `exception`
        should("test exception") {
            // uncomment below to test the property
            //modelInstance.exception shouldBe ("TODO")
        }

    }
}
