/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.GenerateTokenRequest
import pl.com.codenow.ksefclient.models.TokenPermissionType

class GenerateTokenRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GenerateTokenRequest
        //val modelInstance = GenerateTokenRequest()

        // to test the property `permissions` - Uprawnienia przypisane tokenowi.
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

        // to test the property `description` - Opis tokena.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
