/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InitTokenAuthenticationRequest
import pl.com.codenow.ksefclient.models.AuthorizationPolicy
import pl.com.codenow.ksefclient.models.ContextIdentifier

class InitTokenAuthenticationRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InitTokenAuthenticationRequest
        //val modelInstance = InitTokenAuthenticationRequest()

        // to test the property `challenge` - Wygenerowany wcześniej challenge.
        should("test challenge") {
            // uncomment below to test the property
            //modelInstance.challenge shouldBe ("TODO")
        }

        // to test the property `contextIdentifier` - Indentyfikator kontekstu do którego następuje uwierzytelnienie.
        should("test contextIdentifier") {
            // uncomment below to test the property
            //modelInstance.contextIdentifier shouldBe ("TODO")
        }

        // to test the property `encryptedToken` - Zaszyfrowany token wraz z timestampem z challenge'a, w formacie `token|timestamp`.
        should("test encryptedToken") {
            // uncomment below to test the property
            //modelInstance.encryptedToken shouldBe ("TODO")
        }

        // to test the property `authorizationPolicy` - Polityka autoryzacji żądań przy każdym użyciu tokena dostępu.
        should("test authorizationPolicy") {
            // uncomment below to test the property
            //modelInstance.authorizationPolicy shouldBe ("TODO")
        }

    }
}
