/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoiceQueryBuyer
import pl.com.codenow.ksefclient.models.BuyerIdentifierType

class InvoiceQueryBuyerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceQueryBuyer
        //val modelInstance = InvoiceQueryBuyer()

        // to test the property `identifierType` - Typ identyfikatora nabywcy. | Wartość | Opis | | --- | --- | | None | Brak identyfikatora nabywcy | | Other | Inny | | Nip | NIP | | VatUe | VAT UE | 
        should("test identifierType") {
            // uncomment below to test the property
            //modelInstance.identifierType shouldBe ("TODO")
        }

        // to test the property `identifier` - Wartość identyfikatora nabywcy.
        should("test identifier") {
            // uncomment below to test the property
            //modelInstance.identifier shouldBe ("TODO")
        }

    }
}
