/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoiceExportRequest
import pl.com.codenow.ksefclient.models.EncryptionInfo
import pl.com.codenow.ksefclient.models.InvoiceQueryFilters

class InvoiceExportRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceExportRequest
        //val modelInstance = InvoiceExportRequest()

        // to test the property `encryption` - Informacje wymagane do zaszyfrowania wyniku zapytania.
        should("test encryption") {
            // uncomment below to test the property
            //modelInstance.encryption shouldBe ("TODO")
        }

        // to test the property `filters` - Zestaw filtrów do wyszukiwania faktur.
        should("test filters") {
            // uncomment below to test the property
            //modelInstance.filters shouldBe ("TODO")
        }

    }
}
