/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoiceQueryDateRange
import pl.com.codenow.ksefclient.models.InvoiceQueryDateType

class InvoiceQueryDateRangeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceQueryDateRange
        //val modelInstance = InvoiceQueryDateRange()

        // to test the property `dateType` - Typ daty, według której ma być zastosowany zakres. | Wartość | Opis | | --- | --- | | Issue | Data wystawienia faktury. | | Invoicing | Data przyjęcia faktury w systemie KSeF (do dalszego przetwarzania). | | PermanentStorage | Data trwałego zapisu faktury w repozytorium systemu KSeF. | 
        should("test dateType") {
            // uncomment below to test the property
            //modelInstance.dateType shouldBe ("TODO")
        }

        // to test the property `from` - Data początkowa zakresu.
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `to` - Data końcowa zakresu. Jeśli nie zostanie podana, przyjmowana jest bieżąca data i czas w UTC.
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

    }
}
