/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoiceMetadataSeller

class InvoiceMetadataSellerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceMetadataSeller
        //val modelInstance = InvoiceMetadataSeller()

        // to test the property `nip` - Nip sprzedawcy.
        should("test nip") {
            // uncomment below to test the property
            //modelInstance.nip shouldBe ("TODO")
        }

        // to test the property `identifier` - Identyfikator sprzedawcy.
        should("test identifier") {
            // uncomment below to test the property
            //modelInstance.identifier shouldBe ("TODO")
        }

        // to test the property `name` - Nazwa sprzedawcy.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
