/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoiceExportStatusResponse
import pl.com.codenow.ksefclient.models.InvoicePackage
import pl.com.codenow.ksefclient.models.StatusInfo

class InvoiceExportStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoiceExportStatusResponse
        //val modelInstance = InvoiceExportStatusResponse()

        // to test the property `status` - Status eksportu.  | Code | Description | Details | | --- | --- | --- | | 100 | Eksport faktur w toku | - | | 200 | Eksport faktur zakończony sukcesem | - | | 415 | Błąd odszyfrowania dostarczonego klucza  | - | | 500 | Nieznany błąd ({statusCode}) | - |
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `completedDate` - Data zakończenia przetwarzania żądania.
        should("test completedDate") {
            // uncomment below to test the property
            //modelInstance.completedDate shouldBe ("TODO")
        }

        // to test the property ``package`` - Dane paczki faktur przygotowanej do pobrania.
        should("test `package`") {
            // uncomment below to test the property
            //modelInstance.`package` shouldBe ("TODO")
        }

    }
}
