/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.InvoicePackage
import pl.com.codenow.ksefclient.models.InvoicePackagePart

class InvoicePackageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvoicePackage
        //val modelInstance = InvoicePackage()

        // to test the property `invoiceCount` - Łączna liczba faktur w paczce. Maksymalna liczba faktur w paczce to 10 000.
        should("test invoiceCount") {
            // uncomment below to test the property
            //modelInstance.invoiceCount shouldBe ("TODO")
        }

        // to test the property `propertySize` - Rozmiar paczki w bajtach. Maksymalny rozmiar paczki to 1 GiB (1 073 741 824 bajtów).
        should("test propertySize") {
            // uncomment below to test the property
            //modelInstance.propertySize shouldBe ("TODO")
        }

        // to test the property `parts` - Lista dostępnych części paczki do pobrania. Każda część jest zaszyfrowana algorytmem AES-256-CBC z dopełnieniem PKCS#7, przy użyciu klucza symetrycznego przekazanego podczas inicjowania eksportu. Wyniki sortowane są rosnąco według typu daty przekazanej w `DateRange` przy inicjalizacji.
        should("test parts") {
            // uncomment below to test the property
            //modelInstance.parts shouldBe ("TODO")
        }

        // to test the property `isTruncated` - Określa, czy wynik eksportu został ucięty z powodu przekroczenia limitu liczby faktur lub wielkości paczki.
        should("test isTruncated") {
            // uncomment below to test the property
            //modelInstance.isTruncated shouldBe ("TODO")
        }

        // to test the property `lastIssueDate` - Data wystawienia ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `Issue`.
        should("test lastIssueDate") {
            // uncomment below to test the property
            //modelInstance.lastIssueDate shouldBe ("TODO")
        }

        // to test the property `lastInvoicingDate` - Data przyjęcia ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `Invoicing`.
        should("test lastInvoicingDate") {
            // uncomment below to test the property
            //modelInstance.lastInvoicingDate shouldBe ("TODO")
        }

        // to test the property `lastPermanentStorageDate` - Data trwałego zapisu ostatniej faktury ujętej w paczce. Pole występuje wyłącznie wtedy, gdy paczka została ucięta i eksport był filtrowany po typie daty `PermanentStorage`.
        should("test lastPermanentStorageDate") {
            // uncomment below to test the property
            //modelInstance.lastPermanentStorageDate shouldBe ("TODO")
        }

    }
}
