/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.OpenOnlineSessionRequest
import pl.com.codenow.ksefclient.models.EncryptionInfo
import pl.com.codenow.ksefclient.models.FormCode

class OpenOnlineSessionRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of OpenOnlineSessionRequest
        //val modelInstance = OpenOnlineSessionRequest()

        // to test the property `formCode` - Schemat faktur wysyłanych w ramach sesji.  Obsługiwane schematy: | SystemCode | SchemaVersion | Value | | --- | --- | --- | | FA (2) | 1-0E | FA | | FA (3) | 1-0E | FA | | FA_PEF (3) | 2-1 | FA_PEF | | FA_KOR_PEF (3) | 2-1 | FA_PEF | 
        should("test formCode") {
            // uncomment below to test the property
            //modelInstance.formCode shouldBe ("TODO")
        }

        // to test the property `encryption` - Symetryczny klucz szyfrujący pliki XML, zaszyfrowany kluczem publicznym Ministerstwa Finansów.
        should("test encryption") {
            // uncomment below to test the property
            //modelInstance.encryption shouldBe ("TODO")
        }

    }
}
