/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PartUploadRequest

class PartUploadRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PartUploadRequest
        //val modelInstance = PartUploadRequest()

        // to test the property `ordinalNumber` - Numer sekwencyjny części pliku paczki.
        should("test ordinalNumber") {
            // uncomment below to test the property
            //modelInstance.ordinalNumber shouldBe ("TODO")
        }

        // to test the property `method` - Metoda HTTP, której należy użyć przy wysyłce części pliku paczki.
        should("test method") {
            // uncomment below to test the property
            //modelInstance.method shouldBe ("TODO")
        }

        // to test the property `url` - Adres pod który należy wysłać część pliku paczki.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `headers` - Nagłówki, których należy użyć przy wysyłce części pliku paczki.
        should("test headers") {
            // uncomment below to test the property
            //modelInstance.headers shouldBe ("TODO")
        }

    }
}
