/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PermissionsOperationStatusResponse
import pl.com.codenow.ksefclient.models.StatusInfo

class PermissionsOperationStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PermissionsOperationStatusResponse
        //val modelInstance = PermissionsOperationStatusResponse()

        // to test the property `status` - Informacje o aktualnym statusie. | Code | Description | Details | | --- | --- | --- | | 100 | Operacja przyjęta do realizacji | - | | 200 | Operacja zakończona sukcesem | - | | 400 | Operacja zakończona niepowodzeniem | - | | 410 | Podane identyfikatory są niezgodne lub pozostają w niewłaściwej relacji | - | | 420 | Użyte poświadczenia nie mają uprawnień do wykonania tej operacji | - | | 430 | Kontekst identyfikatora nie odpowiada wymaganej roli lub uprawnieniom | - | | 440 | Operacja niedozwolona dla wskazanych powiązań identyfikatorów | - | | 450 | Operacja niedozwolona dla wskazanego identyfikatora lub jego typu | - | | 500 | Nieznany błąd | - |
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

    }
}
