/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PermissionsOperationResponse

class PermissionsOperationResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PermissionsOperationResponse
        //val modelInstance = PermissionsOperationResponse()

        // to test the property `operationReferenceNumber` - Numer referencyjny asynchronicznej operacji nadawania lub odbierania uprawnień.
        should("test operationReferenceNumber") {
            // uncomment below to test the property
            //modelInstance.operationReferenceNumber shouldBe ("TODO")
        }

    }
}
