/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PersonPermissionsQueryRequest
import pl.com.codenow.ksefclient.models.PermissionState
import pl.com.codenow.ksefclient.models.PersonPermissionType
import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorIdentifier
import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorizedIdentifier
import pl.com.codenow.ksefclient.models.PersonPermissionsQueryType
import pl.com.codenow.ksefclient.models.PersonPermissionsTargetIdentifier

class PersonPermissionsQueryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonPermissionsQueryRequest
        //val modelInstance = PersonPermissionsQueryRequest()

        // to test the property `queryType` - Typ zapytania. | Type | Value | | --- | --- | | PermissionsInCurrentContext | Uprawnienia posiadane w aktualnym kontekście | | PermissionsGrantedInCurrentContext | Uprawnienia nadane w aktualnym kontekście |
        should("test queryType") {
            // uncomment below to test the property
            //modelInstance.queryType shouldBe ("TODO")
        }

        // to test the property `authorIdentifier` - Identyfikator osoby lub podmiotu nadającego uprawnienie. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu | | System | Identyfikator systemowy KSeF |
        should("test authorIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorIdentifier shouldBe ("TODO")
        }

        // to test the property `authorizedIdentifier` - Identyfikator osoby lub podmiotu uprawnionego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
        should("test authorizedIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorizedIdentifier shouldBe ("TODO")
        }

        // to test the property `targetIdentifier` - Identyfikator podmiotu docelowego (dla uprawnień pośrednich). | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | AllPartners | Identyfikator oznaczający, że uprawnienie nadane w sposób pośredni jest typu generalnego |
        should("test targetIdentifier") {
            // uncomment below to test the property
            //modelInstance.targetIdentifier shouldBe ("TODO")
        }

        // to test the property `permissionTypes` - Możliwe uprawnienia do filtrowania.
        should("test permissionTypes") {
            // uncomment below to test the property
            //modelInstance.permissionTypes shouldBe ("TODO")
        }

        // to test the property `permissionState` - Stan uprawnienia.  | Type | Value | | --- | --- | | Active | Uprawnienia aktywne | | Inactive | Uprawnienia nieaktywne, nadane w sposób poœredni |
        should("test permissionState") {
            // uncomment below to test the property
            //modelInstance.permissionState shouldBe ("TODO")
        }

    }
}
