/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PersonPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.PersonPermissionType
import pl.com.codenow.ksefclient.models.PersonPermissionsSubjectIdentifier

class PersonPermissionsGrantRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonPermissionsGrantRequest
        //val modelInstance = PersonPermissionsGrantRequest()

        // to test the property `subjectIdentifier` - Identyfikator osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
        should("test subjectIdentifier") {
            // uncomment below to test the property
            //modelInstance.subjectIdentifier shouldBe ("TODO")
        }

        // to test the property `permissions` - Lista nadawanych uprawnień. Każda wartość może wystąpić tylko raz.
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

        // to test the property `description` - Opis nadawanych uprawnień.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
