/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorIdentifier
import pl.com.codenow.ksefclient.models.PersonPermissionsAuthorIdentifierType

class PersonPermissionsAuthorIdentifierTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonPermissionsAuthorIdentifier
        //val modelInstance = PersonPermissionsAuthorIdentifier()

        // to test the property `type` - Typ identyfikatora.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property ``value`` - Wartość identyfikatora. W przypadku typu System należy pozostawić puste. W pozostałych przypadkach pole jest wymagane.
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

    }
}
