/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PublicKeyCertificateUsage

class PublicKeyCertificateUsageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicKeyCertificateUsage
        //val modelInstance = PublicKeyCertificateUsage()

    }
}
