/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.PublicKeyCertificate
import pl.com.codenow.ksefclient.models.PublicKeyCertificateUsage

class PublicKeyCertificateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PublicKeyCertificate
        //val modelInstance = PublicKeyCertificate()

        // to test the property `certificate` - Certyfikat klucza publicznego w formacie DER zakodowany w Base64.
        should("test certificate") {
            // uncomment below to test the property
            //modelInstance.certificate shouldBe ("TODO")
        }

        // to test the property `validFrom` - Data początku obowiązywania certyfikatu.
        should("test validFrom") {
            // uncomment below to test the property
            //modelInstance.validFrom shouldBe ("TODO")
        }

        // to test the property `validTo` - Data końca obowiązywania certyfikatu.
        should("test validTo") {
            // uncomment below to test the property
            //modelInstance.validTo shouldBe ("TODO")
        }

        // to test the property `usage` - Operacje do których może być używany certyfikat. | Wartość | Opis | | --- | --- | | KsefTokenEncryption | Szyfrowanie tokenów KSeF przesyłanych w trakcie procesu uwierzytelniania. | | SymmetricKeyEncryption | Szyfrowanie klucza symetrycznego wykorzystywanego do szyfrowania przesyłanych faktur. | 
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

    }
}
