/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QuerySubordinateEntityRolesResponse
import pl.com.codenow.ksefclient.models.SubordinateEntityRole

class QuerySubordinateEntityRolesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuerySubordinateEntityRolesResponse
        //val modelInstance = QuerySubordinateEntityRolesResponse()

        // to test the property `roles` - Lista ról.
        should("test roles") {
            // uncomment below to test the property
            //modelInstance.roles shouldBe ("TODO")
        }

        // to test the property `hasMore` - Flaga informująca o dostępności kolejnej strony wyników.
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

    }
}
