/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QuerySubunitPermissionsResponse
import pl.com.codenow.ksefclient.models.SubunitPermission

class QuerySubunitPermissionsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QuerySubunitPermissionsResponse
        //val modelInstance = QuerySubunitPermissionsResponse()

        // to test the property `permissions` - Lista uprawnień.
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

        // to test the property `hasMore` - Flaga informująca o dostępności kolejnej strony wyników.
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

    }
}
