/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QueryCertificatesResponse
import pl.com.codenow.ksefclient.models.CertificateListItem

class QueryCertificatesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryCertificatesResponse
        //val modelInstance = QueryCertificatesResponse()

        // to test the property `certificates` - Lista certyfikatów spełniających kryteria wyszukiwania.
        should("test certificates") {
            // uncomment below to test the property
            //modelInstance.certificates shouldBe ("TODO")
        }

        // to test the property `hasMore` - Flaga informująca o dostępności kolejnej strony wyników.
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

    }
}
