/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QueryPeppolProvidersResponse
import pl.com.codenow.ksefclient.models.PeppolProvider

class QueryPeppolProvidersResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryPeppolProvidersResponse
        //val modelInstance = QueryPeppolProvidersResponse()

        // to test the property `peppolProviders` - Lista dostawców usług Peppol.
        should("test peppolProviders") {
            // uncomment below to test the property
            //modelInstance.peppolProviders shouldBe ("TODO")
        }

        // to test the property `hasMore` - Flaga informująca o dostępności kolejnej strony wyników.
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

    }
}
