/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QueryTokensResponse
import pl.com.codenow.ksefclient.models.AuthenticationToken

class QueryTokensResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryTokensResponse
        //val modelInstance = QueryTokensResponse()

        // to test the property `tokens` - Lista tokenów uwierzytelniających.
        should("test tokens") {
            // uncomment below to test the property
            //modelInstance.tokens shouldBe ("TODO")
        }

        // to test the property `continuationToken` - Token służący do pobrania kolejnej strony wyników. Jeśli jest pusty, to nie ma kolejnych stron.
        should("test continuationToken") {
            // uncomment below to test the property
            //modelInstance.continuationToken shouldBe ("TODO")
        }

    }
}
