/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.QueryInvoicesMetadataResponse
import pl.com.codenow.ksefclient.models.InvoiceMetadata

class QueryInvoicesMetadataResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of QueryInvoicesMetadataResponse
        //val modelInstance = QueryInvoicesMetadataResponse()

        // to test the property `hasMore` - Flaga informująca o dostępności kolejnej strony wyników.
        should("test hasMore") {
            // uncomment below to test the property
            //modelInstance.hasMore shouldBe ("TODO")
        }

        // to test the property `invoices` - Lista faktur spełniających kryteria.
        should("test invoices") {
            // uncomment below to test the property
            //modelInstance.invoices shouldBe ("TODO")
        }

    }
}
