/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.RetrieveCertificatesRequest

class RetrieveCertificatesRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RetrieveCertificatesRequest
        //val modelInstance = RetrieveCertificatesRequest()

        // to test the property `certificateSerialNumbers` - Numery seryjne certyfikatów do pobrania.
        should("test certificateSerialNumbers") {
            // uncomment below to test the property
            //modelInstance.certificateSerialNumbers shouldBe ("TODO")
        }

    }
}
