/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.RetrieveCertificatesListItem
import pl.com.codenow.ksefclient.models.KsefCertificateType

class RetrieveCertificatesListItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RetrieveCertificatesListItem
        //val modelInstance = RetrieveCertificatesListItem()

        // to test the property `certificate` - Certyfikat w formacie DER zakodowany w Base64.
        should("test certificate") {
            // uncomment below to test the property
            //modelInstance.certificate shouldBe ("TODO")
        }

        // to test the property `certificateName` - Nazwa własna certyfikatu.
        should("test certificateName") {
            // uncomment below to test the property
            //modelInstance.certificateName shouldBe ("TODO")
        }

        // to test the property `certificateSerialNumber` - Numer seryjny certyfikatu.
        should("test certificateSerialNumber") {
            // uncomment below to test the property
            //modelInstance.certificateSerialNumber shouldBe ("TODO")
        }

        // to test the property `certificateType` - Typ certyfikatu. | Wartość | Opis | | --- | --- | | Authentication | Certyfikat używany do uwierzytelnienia w systemie. | | Offline | Certyfikat używany wyłącznie do potwierdzania autentyczności wystawcy i integralności faktury w trybie offline | 
        should("test certificateType") {
            // uncomment below to test the property
            //modelInstance.certificateType shouldBe ("TODO")
        }

    }
}
