/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.RevokeCertificateRequest
import pl.com.codenow.ksefclient.models.CertificateRevocationReason

class RevokeCertificateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RevokeCertificateRequest
        //val modelInstance = RevokeCertificateRequest()

        // to test the property `revocationReason` - Powód unieważnienia certyfikatu. | Wartość | Opis | | --- | --- | | Unspecified | Nieokreślony. | | Superseded | Certyfikat został zastąpiony przez inny. | | KeyCompromise | Klucz prywatny powiązany z certyfikatem został skompromitowany. | 
        should("test revocationReason") {
            // uncomment below to test the property
            //modelInstance.revocationReason shouldBe ("TODO")
        }

    }
}
