/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SendInvoiceRequest

class SendInvoiceRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SendInvoiceRequest
        //val modelInstance = SendInvoiceRequest()

        // to test the property `invoiceHash` - Skrót SHA256 oryginalnej faktury, zakodowany w formacie Base64.
        should("test invoiceHash") {
            // uncomment below to test the property
            //modelInstance.invoiceHash shouldBe ("TODO")
        }

        // to test the property `invoiceSize` - Rozmiar oryginalnej faktury w bajtach.
        should("test invoiceSize") {
            // uncomment below to test the property
            //modelInstance.invoiceSize shouldBe ("TODO")
        }

        // to test the property `encryptedInvoiceHash` - Skrót SHA256 zaszyfrowanej faktury, zakodowany w formacie Base64.
        should("test encryptedInvoiceHash") {
            // uncomment below to test the property
            //modelInstance.encryptedInvoiceHash shouldBe ("TODO")
        }

        // to test the property `encryptedInvoiceSize` - Rozmiar zaszyfrowanej faktury w bajtach.
        should("test encryptedInvoiceSize") {
            // uncomment below to test the property
            //modelInstance.encryptedInvoiceSize shouldBe ("TODO")
        }

        // to test the property `encryptedInvoiceContent` - Faktura zaszyfrowana algorytmem AES-256-CBC z dopełnianiem PKCS#7 (kluczem przekazanym przy otwarciu sesji), zakodowana w formacie Base64.
        should("test encryptedInvoiceContent") {
            // uncomment below to test the property
            //modelInstance.encryptedInvoiceContent shouldBe ("TODO")
        }

        // to test the property `offlineMode` - Określa, czy podatnik deklaruje tryb fakturowania \"offline\" dla przesyłanego dokumentu.
        should("test offlineMode") {
            // uncomment below to test the property
            //modelInstance.offlineMode shouldBe ("TODO")
        }

        // to test the property `hashOfCorrectedInvoice` - Skrót SHA256 korygowanej faktury, zakodowany w formacie Base64. Wymagany przy wysyłaniu korekty technicznej faktury.
        should("test hashOfCorrectedInvoice") {
            // uncomment below to test the property
            //modelInstance.hashOfCorrectedInvoice shouldBe ("TODO")
        }

    }
}
