/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SessionStatusResponse
import pl.com.codenow.ksefclient.models.StatusInfo
import pl.com.codenow.ksefclient.models.UpoResponse

class SessionStatusResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionStatusResponse
        //val modelInstance = SessionStatusResponse()

        // to test the property `status` - Informacje o aktualnym statusie.              Sesja wsadowa: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja wsadowa rozpoczęta | - | | 150 | Trwa przetwarzanie | - | | 200 | Sesja wsadowa przetworzona pomyślnie | - | | 405 | Błąd weryfikacji poprawności dostarczonych elementów paczki | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 430 | Błąd dekompresji pierwotnego archiwum | - | | 435 | Błąd odszyfrowania zaszyfrowanych części archiwum | - | | 440 | Sesja anulowana, przekroczono czas wysyłki | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | 500 | Nieznany błąd ({statusCode}) | - |  Sesja interaktywna: | Code | Description | Details | | --- | --- | --- | | 100 | Sesja interaktywna otwarta | - | | 170 | Sesja interaktywna zamknięta | - | | 200 | Sesja interaktywna przetworzona pomyślnie | - | | 415 | Błąd odszyfrowania dostarczonego klucza | - | | 440 | Sesja anulowana, nie przesłano faktur | - | | 445 | Błąd weryfikacji, brak poprawnych faktur | - | | * | description missing | - |
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `validUntil` - Termin ważności sesji. Po jego upływie sesja zostanie automatycznie zamknięta.
        should("test validUntil") {
            // uncomment below to test the property
            //modelInstance.validUntil shouldBe ("TODO")
        }

        // to test the property `upo` - Informacja o UPO sesyjnym, zwracana gdy sesja została zamknięta i UPO zostało wygenerowane.
        should("test upo") {
            // uncomment below to test the property
            //modelInstance.upo shouldBe ("TODO")
        }

        // to test the property `invoiceCount` - Liczba przyjętych faktur w ramach sesji.
        should("test invoiceCount") {
            // uncomment below to test the property
            //modelInstance.invoiceCount shouldBe ("TODO")
        }

        // to test the property `successfulInvoiceCount` - Liczba faktur przeprocesowanych w ramach sesji z sukcesem .
        should("test successfulInvoiceCount") {
            // uncomment below to test the property
            //modelInstance.successfulInvoiceCount shouldBe ("TODO")
        }

        // to test the property `failedInvoiceCount` - Liczba faktur przeprocesowanych w ramach sesji z błędem.
        should("test failedInvoiceCount") {
            // uncomment below to test the property
            //modelInstance.failedInvoiceCount shouldBe ("TODO")
        }

    }
}
