/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SessionsQueryResponseItem
import pl.com.codenow.ksefclient.models.StatusInfo

class SessionsQueryResponseItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SessionsQueryResponseItem
        //val modelInstance = SessionsQueryResponseItem()

        // to test the property `referenceNumber` - Numer referencyjny sesji.
        should("test referenceNumber") {
            // uncomment below to test the property
            //modelInstance.referenceNumber shouldBe ("TODO")
        }

        // to test the property `status` - Status sesji.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `dateCreated` - Data utowrzenia sesji.
        should("test dateCreated") {
            // uncomment below to test the property
            //modelInstance.dateCreated shouldBe ("TODO")
        }

        // to test the property `dateUpdated` - Data ostatniej aktywności w ramach sesji.
        should("test dateUpdated") {
            // uncomment below to test the property
            //modelInstance.dateUpdated shouldBe ("TODO")
        }

        // to test the property `totalInvoiceCount` - Łączna liczba faktur (uwzględnia również te w trakcie przetwarzania).
        should("test totalInvoiceCount") {
            // uncomment below to test the property
            //modelInstance.totalInvoiceCount shouldBe ("TODO")
        }

        // to test the property `successfulInvoiceCount` - Liczba poprawnie przetworzonych faktur.
        should("test successfulInvoiceCount") {
            // uncomment below to test the property
            //modelInstance.successfulInvoiceCount shouldBe ("TODO")
        }

        // to test the property `failedInvoiceCount` - Liczba błędnie przetworzonych faktur.
        should("test failedInvoiceCount") {
            // uncomment below to test the property
            //modelInstance.failedInvoiceCount shouldBe ("TODO")
        }

        // to test the property `validUntil` - Termin ważności sesji. Po jego upływie sesja interaktywna zostanie automatycznie zamknięta.
        should("test validUntil") {
            // uncomment below to test the property
            //modelInstance.validUntil shouldBe ("TODO")
        }

    }
}
