/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SubordinateEntityRole
import pl.com.codenow.ksefclient.models.SubordinateEntityRoleType
import pl.com.codenow.ksefclient.models.SubordinateRoleSubordinateEntityIdentifierType

class SubordinateEntityRoleTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubordinateEntityRole
        //val modelInstance = SubordinateEntityRole()

        // to test the property `subordinateEntityIdentifier` - Identyfikator podmiotu podrzędnego.
        should("test subordinateEntityIdentifier") {
            // uncomment below to test the property
            //modelInstance.subordinateEntityIdentifier shouldBe ("TODO")
        }

        // to test the property `subordinateEntityIdentifierType` - Typ identyfikatora podmiotu podrzędnego.
        should("test subordinateEntityIdentifierType") {
            // uncomment below to test the property
            //modelInstance.subordinateEntityIdentifierType shouldBe ("TODO")
        }

        // to test the property `role` - Powiązanie.
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `description` - Opis.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `startDate` - Data rozpoczęcia obowiązywania powiązania.
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

    }
}
