/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SubunitPermission
import pl.com.codenow.ksefclient.models.SubunitPermissionScope
import pl.com.codenow.ksefclient.models.SubunitPermissionsAuthorIdentifierType
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubjectIdentifierType
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubunitIdentifierType

class SubunitPermissionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubunitPermission
        //val modelInstance = SubunitPermission()

        // to test the property `id` - Identyfikator uprawnienia.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `authorizedIdentifier` - Identyfikator uprawnionego.
        should("test authorizedIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorizedIdentifier shouldBe ("TODO")
        }

        // to test the property `authorizedIdentifierType` - Typ identyfikatora uprawnionego.
        should("test authorizedIdentifierType") {
            // uncomment below to test the property
            //modelInstance.authorizedIdentifierType shouldBe ("TODO")
        }

        // to test the property `subunitIdentifier` - Identyfikator podmiotu podrzędnego.
        should("test subunitIdentifier") {
            // uncomment below to test the property
            //modelInstance.subunitIdentifier shouldBe ("TODO")
        }

        // to test the property `subunitIdentifierType` - Typ identyfikatora podmiotu podrzędnego.
        should("test subunitIdentifierType") {
            // uncomment below to test the property
            //modelInstance.subunitIdentifierType shouldBe ("TODO")
        }

        // to test the property `authorIdentifier` - Identyfikator uprawniającego.
        should("test authorIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorIdentifier shouldBe ("TODO")
        }

        // to test the property `authorIdentifierType` - Typ identyfikatora uprawniającego.
        should("test authorIdentifierType") {
            // uncomment below to test the property
            //modelInstance.authorIdentifierType shouldBe ("TODO")
        }

        // to test the property `permissionScope` - Uprawnienie.
        should("test permissionScope") {
            // uncomment below to test the property
            //modelInstance.permissionScope shouldBe ("TODO")
        }

        // to test the property `description` - Opis uprawnienia.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `startDate` - Data rozpoczęcia obowiązywania uprawnienia.
        should("test startDate") {
            // uncomment below to test the property
            //modelInstance.startDate shouldBe ("TODO")
        }

    }
}
