/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SubunitPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.SubunitPermissionsContextIdentifier
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubjectIdentifier

class SubunitPermissionsGrantRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubunitPermissionsGrantRequest
        //val modelInstance = SubunitPermissionsGrantRequest()

        // to test the property `subjectIdentifier` - Identyfikator podmiotu lub osoby fizycznej. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | Pesel | 11 cyfrowy numer PESEL | | Fingerprint | Odcisk palca certyfikatu |
        should("test subjectIdentifier") {
            // uncomment below to test the property
            //modelInstance.subjectIdentifier shouldBe ("TODO")
        }

        // to test the property `contextIdentifier` - Identyfikator podmiotu podrzędnego. | Type | Value | | --- | --- | | Nip | 10 cyfrowy numer NIP | | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` |
        should("test contextIdentifier") {
            // uncomment below to test the property
            //modelInstance.contextIdentifier shouldBe ("TODO")
        }

        // to test the property `description` - Opis nadawanych uprawnień.
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

    }
}
