/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.SubunitPermissionsQueryRequest
import pl.com.codenow.ksefclient.models.SubunitPermissionsSubunitIdentifier

class SubunitPermissionsQueryRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SubunitPermissionsQueryRequest
        //val modelInstance = SubunitPermissionsQueryRequest()

        // to test the property `subunitIdentifier` - Identyfikator jednostki lub podmiotu podrzędnego. | Type | Value | | --- | --- | | InternalId | Dwuczłonowy identyfikator składający się z numeru NIP i 5 cyfr: `{nip}-{5_cyfr}` | | Nip | 10 cyfrowy numer NIP |
        should("test subunitIdentifier") {
            // uncomment below to test the property
            //modelInstance.subunitIdentifier shouldBe ("TODO")
        }

    }
}
