/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.TestDataPermissionsRevokeRequest
import pl.com.codenow.ksefclient.models.TestDataAuthorizedIdentifier
import pl.com.codenow.ksefclient.models.TestDataContextIdentifier

class TestDataPermissionsRevokeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestDataPermissionsRevokeRequest
        //val modelInstance = TestDataPermissionsRevokeRequest()

        // to test the property `contextIdentifier`
        should("test contextIdentifier") {
            // uncomment below to test the property
            //modelInstance.contextIdentifier shouldBe ("TODO")
        }

        // to test the property `authorizedIdentifier`
        should("test authorizedIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorizedIdentifier shouldBe ("TODO")
        }

    }
}
