/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.TestDataPermissionsGrantRequest
import pl.com.codenow.ksefclient.models.TestDataAuthorizedIdentifier
import pl.com.codenow.ksefclient.models.TestDataContextIdentifier
import pl.com.codenow.ksefclient.models.TestDataPermission

class TestDataPermissionsGrantRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestDataPermissionsGrantRequest
        //val modelInstance = TestDataPermissionsGrantRequest()

        // to test the property `contextIdentifier`
        should("test contextIdentifier") {
            // uncomment below to test the property
            //modelInstance.contextIdentifier shouldBe ("TODO")
        }

        // to test the property `authorizedIdentifier`
        should("test authorizedIdentifier") {
            // uncomment below to test the property
            //modelInstance.authorizedIdentifier shouldBe ("TODO")
        }

        // to test the property `permissions`
        should("test permissions") {
            // uncomment below to test the property
            //modelInstance.permissions shouldBe ("TODO")
        }

    }
}
