/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.TokenInfo

class TokenInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TokenInfo
        //val modelInstance = TokenInfo()

        // to test the property `token` - Token w formacie JWT.
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `validUntil` - Data ważności tokena.
        should("test validUntil") {
            // uncomment below to test the property
            //modelInstance.validUntil shouldBe ("TODO")
        }

    }
}
