/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package pl.com.codenow.ksefclient.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import pl.com.codenow.ksefclient.models.UpoResponse
import pl.com.codenow.ksefclient.models.UpoPageResponse

class UpoResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpoResponse
        //val modelInstance = UpoResponse()

        // to test the property `pages` - Lista stron UPO.
        should("test pages") {
            // uncomment below to test the property
            //modelInstance.pages shouldBe ("TODO")
        }

    }
}
